/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Controlador.ClienteControlador;
import Controlador.PersonaControlador;
import Dao.DaoPersona;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import logica.Cliente;

/**
 *
 * @author juandapp
 */
public class JPCliente extends javax.swing.JPanel {

    /**
     * Creates new form JPCliente
     */
   ClienteControlador clienteControlador;
   
    public JPCliente() {
        initComponents();
        clienteControlador= new ClienteControlador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTFIdentificacion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCBGenero = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTFFechaNacimiento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFDireccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTFEmail = new javax.swing.JTextField();
        jBLimpiarCrear = new javax.swing.JButton();
        jBCrear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTFIdentificacion1 = new javax.swing.JTextField();
        jBConsultar = new javax.swing.JButton();
        jTFNombre1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTResultados = new javax.swing.JTable();
        jBLimpiarConsultar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jTFIdentificacion2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTFNombre2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jCBGenero1 = new javax.swing.JComboBox();
        jTFFechaNacimiento1 = new javax.swing.JTextField();
        jTFTelefono1 = new javax.swing.JTextField();
        jTFDireccion1 = new javax.swing.JTextField();
        jTFEmail1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jBModificar = new javax.swing.JButton();

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));
        jPanel5.setLayout(null);
        jPanel5.add(jLabel13);
        jLabel13.setBounds(18, 182, 0, 0);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));
        jPanel4.setLayout(null);

        jPanel1.setLayout(null);

        jLabel3.setText("Identificacion");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 20, 83, 17);

        jTFIdentificacion.setColumns(20);
        jPanel1.add(jTFIdentificacion);
        jTFIdentificacion.setBounds(160, 10, 272, 27);

        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 50, 52, 17);

        jTFNombre.setColumns(20);
        jPanel1.add(jTFNombre);
        jTFNombre.setBounds(160, 40, 272, 27);

        jLabel2.setText("Genero");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 80, 47, 17);

        jCBGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Femenino", "Masculino" }));
        jCBGenero.setName(""); // NOI18N
        jPanel1.add(jCBGenero);
        jCBGenero.setBounds(160, 70, 113, 27);

        jLabel5.setText("Fecha de nacimiento");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 110, 133, 17);

        jTFFechaNacimiento.setColumns(20);
        jPanel1.add(jTFFechaNacimiento);
        jTFFechaNacimiento.setBounds(160, 100, 272, 27);

        jLabel4.setText("Telefono");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 140, 54, 17);

        jTFTelefono.setColumns(20);
        jPanel1.add(jTFTelefono);
        jTFTelefono.setBounds(160, 130, 272, 27);

        jLabel8.setText("Direccion");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 170, 59, 17);

        jTFDireccion.setColumns(20);
        jPanel1.add(jTFDireccion);
        jTFDireccion.setBounds(160, 160, 272, 27);

        jLabel9.setText("Email");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 200, 35, 17);

        jTFEmail.setColumns(20);
        jPanel1.add(jTFEmail);
        jTFEmail.setBounds(160, 190, 272, 27);

        jBLimpiarCrear.setText("Limpiar");
        jBLimpiarCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarCrearActionPerformed(evt);
            }
        });
        jPanel1.add(jBLimpiarCrear);
        jBLimpiarCrear.setBounds(230, 230, 80, 33);

        jBCrear.setText("Crear");
        jBCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearActionPerformed(evt);
            }
        });
        jPanel1.add(jBCrear);
        jBCrear.setBounds(360, 230, 70, 33);

        jTabbedPane1.addTab("Crear", jPanel1);

        jPanel2.setLayout(null);

        jLabel16.setText("Identificacion");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(10, 20, 83, 17);

        jTFIdentificacion1.setColumns(20);
        jPanel2.add(jTFIdentificacion1);
        jTFIdentificacion1.setBounds(160, 10, 190, 27);

        jBConsultar.setText("Consultar");
        jPanel2.add(jBConsultar);
        jBConsultar.setBounds(360, 10, 90, 33);

        jTFNombre1.setColumns(20);
        jPanel2.add(jTFNombre1);
        jTFNombre1.setBounds(160, 40, 190, 27);

        jLabel6.setText("Nombre");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 50, 52, 17);

        jTResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Nombre", "Direccion", "Telefono", "Email", "Genero"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTResultadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTResultados);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 80, 480, 125);

        jBLimpiarConsultar.setText("Limpiar");
        jBLimpiarConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarConsultarActionPerformed(evt);
            }
        });
        jPanel2.add(jBLimpiarConsultar);
        jBLimpiarConsultar.setBounds(360, 40, 90, 33);

        jTabbedPane1.addTab("Consultar", jPanel2);

        jPanel3.setLayout(null);

        jLabel19.setText("Identificacion");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(10, 20, 83, 17);

        jTFIdentificacion2.setColumns(20);
        jPanel3.add(jTFIdentificacion2);
        jTFIdentificacion2.setBounds(160, 10, 272, 27);

        jLabel10.setText("Nombre");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 50, 52, 17);

        jTFNombre2.setColumns(20);
        jPanel3.add(jTFNombre2);
        jTFNombre2.setBounds(160, 40, 272, 27);

        jLabel12.setText("Genero");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(10, 80, 47, 17);

        jCBGenero1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Femenino", "Masculino" }));
        jCBGenero1.setName(""); // NOI18N
        jPanel3.add(jCBGenero1);
        jCBGenero1.setBounds(160, 70, 113, 27);

        jTFFechaNacimiento1.setColumns(20);
        jPanel3.add(jTFFechaNacimiento1);
        jTFFechaNacimiento1.setBounds(160, 100, 272, 27);

        jTFTelefono1.setColumns(20);
        jPanel3.add(jTFTelefono1);
        jTFTelefono1.setBounds(160, 130, 272, 27);

        jTFDireccion1.setColumns(20);
        jPanel3.add(jTFDireccion1);
        jTFDireccion1.setBounds(160, 160, 272, 27);

        jTFEmail1.setColumns(20);
        jPanel3.add(jTFEmail1);
        jTFEmail1.setBounds(160, 190, 272, 27);

        jLabel18.setText("Email");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(10, 200, 35, 17);

        jLabel17.setText("Direccion");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(10, 170, 59, 17);

        jLabel11.setText("Telefono");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 140, 54, 17);

        jLabel14.setText("Fecha de nacimiento");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(10, 110, 133, 17);

        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });
        jPanel3.add(jBModificar);
        jBModificar.setBounds(331, 230, 90, 33);

        jTabbedPane1.addTab("Modificar", jPanel3);

        jPanel4.add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 20, 500, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBLimpiarCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarCrearActionPerformed
        jTFDireccion.setText("");
        jTFEmail.setText("");
        jTFFechaNacimiento.setText("");
        jTFIdentificacion.setText("");
        jTFNombre.setText("");
        jTFTelefono.setText("");
        jCBGenero.setSelectedIndex(0);
    }//GEN-LAST:event_jBLimpiarCrearActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        // TODO add your handling code here:
        Cliente consultar = null;
        try {
            consultar = clienteControlador.consultar(Integer.parseInt(jTFIdentificacion1.getText()));
        } catch (Exception e) {
        }
        if ((consultar != null) && (consultar.getId_c().getId_p()!=0)) {
            Object[][] s = new Object[1][6];
            s[0][0] = consultar.getId_c().getId_p();
            s[0][1] = consultar.getId_c().getNombre_p();
            s[0][2] = consultar.getId_c().getDireccion_p();
            s[0][3] = consultar.getId_c().getTelefono_p();
            s[0][4] = consultar.getId_c().getEmail_p();
            s[0][5] = consultar.getId_c().getGenero_p();


            TableModel myModel = new javax.swing.table.DefaultTableModel(s, new String[]{"Identificacion", "Nombre", 
                "Direccion", "Telefono","Email","Genero"}) {

                boolean[] canEdit = new boolean[]{false, false, false, false,false,false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            };
           ///remover filas
            jTResultados.setModel(myModel);
            jTResultados.setRowSorter(new TableRowSorter(myModel));}
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearActionPerformed
       int guardar = -1;
        try {
            guardar = clienteControlador.guardar(
                    Integer.parseInt(jTFIdentificacion.getText()),
                    jTFNombre.getText(),
                    jTFDireccion.getText(),
                    jTFTelefono.getText(),
                    jTFEmail.getText(),jCBGenero.getSelectedItem().toString());

        } catch (Exception e) {
        }

        if (guardar == -1) {
            JOptionPane.showMessageDialog(this, "No su pudo crear el cliente", "Error Base Datos", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Cliente Creado correctamente", "Base Datos", JOptionPane.INFORMATION_MESSAGE);
            jTFIdentificacion1.setText(jTFIdentificacion.getText());
            jBConsultar.doClick();
            jTabbedPane1.setSelectedIndex(1);
            
        }
    //GEN-LAST:event_jBCrearActionPerformed


    }//GEN-LAST:event_jBCrearActionPerformed

    private void jBLimpiarConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBLimpiarConsultarActionPerformed

    private void jTResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTResultadosMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTResultados.getSelectedRow();
        jTFIdentificacion1.setText("" + jTResultados.getModel().getValueAt(selectedRow, 0));
        jTFNombre1.setText("" + jTResultados.getModel().getValueAt(selectedRow, 1));
       
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jTResultadosMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConsultar;
    private javax.swing.JButton jBCrear;
    private javax.swing.JButton jBLimpiarConsultar;
    private javax.swing.JButton jBLimpiarCrear;
    private javax.swing.JButton jBModificar;
    private javax.swing.JComboBox jCBGenero;
    private javax.swing.JComboBox jCBGenero1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFDireccion;
    private javax.swing.JTextField jTFDireccion1;
    private javax.swing.JTextField jTFEmail;
    private javax.swing.JTextField jTFEmail1;
    private javax.swing.JTextField jTFFechaNacimiento;
    private javax.swing.JTextField jTFFechaNacimiento1;
    private javax.swing.JTextField jTFIdentificacion;
    private javax.swing.JTextField jTFIdentificacion1;
    private javax.swing.JTextField jTFIdentificacion2;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFNombre1;
    private javax.swing.JTextField jTFNombre2;
    private javax.swing.JTextField jTFTelefono;
    private javax.swing.JTextField jTFTelefono1;
    private javax.swing.JTable jTResultados;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
