/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author juandapp
 */
public class JPCliente extends javax.swing.JPanel {

    /**
     * Creates new form JPCliente
     */
    public JPCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTFIdentificacion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCBGenero = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTFFechaNacimiento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFDireccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTFEmail = new javax.swing.JTextField();
        jBLimpiar = new javax.swing.JButton();
        jBCrear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTFIdentificacion1 = new javax.swing.JTextField();
        jBConsultar = new javax.swing.JButton();
        jTFNombre1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTResultados = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jTFIdentificacion2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTFNombre2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jCBGenero1 = new javax.swing.JComboBox();
        jTFFechaNacimiento1 = new javax.swing.JTextField();
        jTFTelefono1 = new javax.swing.JTextField();
        jTFDireccion1 = new javax.swing.JTextField();
        jTFEmail1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jBModificar = new javax.swing.JButton();

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));
        jPanel5.setLayout(null);
        jPanel5.add(jLabel13);
        jLabel13.setBounds(18, 182, 0, 0);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));
        jPanel4.setLayout(null);

        jPanel1.setLayout(null);

        jLabel3.setText("Identificacion");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 20, 93, 18);

        jTFIdentificacion.setColumns(20);
        jPanel1.add(jTFIdentificacion);
        jTFIdentificacion.setBounds(160, 10, 270, 28);

        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 50, 57, 18);

        jTFNombre.setColumns(20);
        jPanel1.add(jTFNombre);
        jTFNombre.setBounds(160, 40, 270, 28);

        jLabel2.setText("Genero");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 80, 52, 18);

        jCBGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Femenino", "Masculino" }));
        jCBGenero.setName(""); // NOI18N
        jPanel1.add(jCBGenero);
        jCBGenero.setBounds(160, 70, 119, 28);

        jLabel5.setText("Fecha de nacimiento");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 110, 143, 18);

        jTFFechaNacimiento.setColumns(20);
        jPanel1.add(jTFFechaNacimiento);
        jTFFechaNacimiento.setBounds(160, 100, 270, 28);

        jLabel4.setText("Telefono");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 140, 64, 18);

        jTFTelefono.setColumns(20);
        jPanel1.add(jTFTelefono);
        jTFTelefono.setBounds(160, 130, 270, 28);

        jLabel8.setText("Direccion");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 170, 66, 18);

        jTFDireccion.setColumns(20);
        jPanel1.add(jTFDireccion);
        jTFDireccion.setBounds(160, 160, 270, 28);

        jLabel9.setText("Email");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 200, 37, 18);

        jTFEmail.setColumns(20);
        jPanel1.add(jTFEmail);
        jTFEmail.setBounds(160, 190, 270, 28);

        jBLimpiar.setText("Limpiar");
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(jBLimpiar);
        jBLimpiar.setBounds(230, 230, 80, 30);

        jBCrear.setText("Crear");
        jPanel1.add(jBCrear);
        jBCrear.setBounds(360, 230, 70, 30);

        jTabbedPane1.addTab("Crear", jPanel1);

        jPanel2.setLayout(null);

        jLabel16.setText("Identificacion");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(10, 20, 93, 18);

        jTFIdentificacion1.setColumns(20);
        jPanel2.add(jTFIdentificacion1);
        jTFIdentificacion1.setBounds(160, 10, 190, 28);

        jBConsultar.setText("Consultar");
        jPanel2.add(jBConsultar);
        jBConsultar.setBounds(360, 10, 90, 30);

        jTFNombre1.setColumns(20);
        jPanel2.add(jTFNombre1);
        jTFNombre1.setBounds(160, 40, 190, 28);

        jLabel6.setText("Nombre");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 50, 57, 18);

        jTResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Nombre", "Direccion", "Telefono", "Email", "Genero"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTResultados);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 80, 480, 125);

        jTabbedPane1.addTab("Consultar", jPanel2);

        jPanel3.setLayout(null);

        jLabel19.setText("Identificacion");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(10, 20, 93, 18);

        jTFIdentificacion2.setColumns(20);
        jPanel3.add(jTFIdentificacion2);
        jTFIdentificacion2.setBounds(160, 10, 270, 28);

        jLabel10.setText("Nombre");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 50, 57, 18);

        jTFNombre2.setColumns(20);
        jPanel3.add(jTFNombre2);
        jTFNombre2.setBounds(160, 40, 270, 28);

        jLabel12.setText("Genero");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(10, 80, 52, 18);

        jCBGenero1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Femenino", "Masculino" }));
        jCBGenero1.setName(""); // NOI18N
        jPanel3.add(jCBGenero1);
        jCBGenero1.setBounds(160, 70, 119, 28);

        jTFFechaNacimiento1.setColumns(20);
        jPanel3.add(jTFFechaNacimiento1);
        jTFFechaNacimiento1.setBounds(160, 100, 270, 28);

        jTFTelefono1.setColumns(20);
        jPanel3.add(jTFTelefono1);
        jTFTelefono1.setBounds(160, 130, 270, 28);

        jTFDireccion1.setColumns(20);
        jPanel3.add(jTFDireccion1);
        jTFDireccion1.setBounds(160, 160, 270, 28);

        jTFEmail1.setColumns(20);
        jPanel3.add(jTFEmail1);
        jTFEmail1.setBounds(160, 190, 270, 28);

        jLabel18.setText("Email");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(10, 200, 37, 18);

        jLabel17.setText("Direccion");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(10, 170, 66, 18);

        jLabel11.setText("Telefono");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 140, 64, 18);

        jLabel14.setText("Fecha de nacimiento");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(10, 110, 143, 18);

        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });
        jPanel3.add(jBModificar);
        jBModificar.setBounds(331, 230, 90, 30);

        jTabbedPane1.addTab("Modificar", jPanel3);

        jPanel4.add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 20, 500, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        jTFDireccion.setText("");
        jTFEmail.setText("");
        jTFFechaNacimiento.setText("");
        jTFIdentificacion.setText("");
        jTFNombre.setText("");
        jTFTelefono.setText("");
        jCBGenero.setSelectedIndex(0);
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBModificarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConsultar;
    private javax.swing.JButton jBCrear;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JComboBox jCBGenero;
    private javax.swing.JComboBox jCBGenero1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFDireccion;
    private javax.swing.JTextField jTFDireccion1;
    private javax.swing.JTextField jTFEmail;
    private javax.swing.JTextField jTFEmail1;
    private javax.swing.JTextField jTFFechaNacimiento;
    private javax.swing.JTextField jTFFechaNacimiento1;
    private javax.swing.JTextField jTFIdentificacion;
    private javax.swing.JTextField jTFIdentificacion1;
    private javax.swing.JTextField jTFIdentificacion2;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFNombre1;
    private javax.swing.JTextField jTFNombre2;
    private javax.swing.JTextField jTFTelefono;
    private javax.swing.JTextField jTFTelefono1;
    private javax.swing.JTable jTResultados;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
