/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import GeneradorReportes.Reportes;

/**
 *
 * @author juandapp
 */
public class JPCotizacion extends javax.swing.JPanel {

    /**
     * Creates new form JPCotizacion
     */
    Reportes reporte;
    public JPCotizacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCotizacion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTFMarca = new javax.swing.JTextField();
        jTFModelo = new javax.swing.JTextField();
        jTFValor = new javax.swing.JTextField();
        jBLimpiar = new javax.swing.JButton();
        jBGenerar = new javax.swing.JButton();
        jTFColor = new javax.swing.JTextField();
        jTFLinea = new javax.swing.JTextField();
        jTFCojineria = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        jPanelCotizacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Cotizacion"));
        jPanelCotizacion.setLayout(null);

        jLabel1.setText("Modelo");
        jPanelCotizacion.add(jLabel1);
        jLabel1.setBounds(10, 30, 150, 17);

        jLabel4.setText("Linea");
        jPanelCotizacion.add(jLabel4);
        jLabel4.setBounds(10, 60, 70, 17);

        jLabel8.setText("Marca");
        jPanelCotizacion.add(jLabel8);
        jLabel8.setBounds(10, 90, 70, 17);

        jLabel9.setText("Color");
        jPanelCotizacion.add(jLabel9);
        jLabel9.setBounds(10, 120, 80, 17);

        jLabel10.setText("Valor");
        jPanelCotizacion.add(jLabel10);
        jLabel10.setBounds(10, 180, 80, 17);

        jTFMarca.setColumns(20);
        jPanelCotizacion.add(jTFMarca);
        jTFMarca.setBounds(172, 90, 210, 27);

        jTFModelo.setColumns(20);
        jPanelCotizacion.add(jTFModelo);
        jTFModelo.setBounds(172, 30, 210, 27);

        jTFValor.setColumns(20);
        jPanelCotizacion.add(jTFValor);
        jTFValor.setBounds(172, 180, 210, 27);

        jBLimpiar.setText("Limpiar");
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });
        jPanelCotizacion.add(jBLimpiar);
        jBLimpiar.setBounds(270, 250, 100, 33);

        jBGenerar.setText("Generar");
        jBGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGenerarActionPerformed(evt);
            }
        });
        jPanelCotizacion.add(jBGenerar);
        jBGenerar.setBounds(110, 250, 100, 33);

        jTFColor.setColumns(20);
        jPanelCotizacion.add(jTFColor);
        jTFColor.setBounds(172, 120, 210, 27);

        jTFLinea.setColumns(20);
        jPanelCotizacion.add(jTFLinea);
        jTFLinea.setBounds(172, 60, 210, 27);

        jTFCojineria.setColumns(20);
        jPanelCotizacion.add(jTFCojineria);
        jTFCojineria.setBounds(172, 150, 210, 27);

        jLabel12.setText("Cojineria");
        jPanelCotizacion.add(jLabel12);
        jLabel12.setBounds(10, 150, 80, 17);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCotizacion, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCotizacion, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
// TODO add your handling code here:
        jTFCojineria.setText("");
        jTFColor.setText("");
        jTFMarca.setText("");
        jTFModelo.setText("");
        jTFValor.setText("");
        jTFLinea.setText("");
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jBGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGenerarActionPerformed
        // TODO add your handling code here:
        //FALTA INGRESAR DATOS A UNA TABLA DE COTIZACIONES
        reporte=new Reportes();
        reporte.generarReporte("reporteCotizacion");
        
    }//GEN-LAST:event_jBGenerarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGenerar;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelCotizacion;
    private javax.swing.JTextField jTFCojineria;
    private javax.swing.JTextField jTFColor;
    private javax.swing.JTextField jTFLinea;
    private javax.swing.JTextField jTFMarca;
    private javax.swing.JTextField jTFModelo;
    private javax.swing.JTextField jTFValor;
    // End of variables declaration//GEN-END:variables
}
