/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author juandapp
 */
public class JPOAlistamiento extends javax.swing.JPanel {

    /**
     * Creates new form JPOAlistamiento
     */
    public JPOAlistamiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTFModelo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTFColor = new javax.swing.JTextField();
        jTFNoChasis = new javax.swing.JTextField();
        jTFMarca = new javax.swing.JTextField();
        jTFLinea = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTResultados = new javax.swing.JTable();
        jBConsultarVehiculo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jCBDisponible = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTFIdentificacion = new javax.swing.JTextField();
        jTFNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTResultados1 = new javax.swing.JTable();
        jBConsultarCliente = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTFIdentificacion1 = new javax.swing.JTextField();
        jTFNombre1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jCBCargo1 = new javax.swing.JComboBox();
        jBConsultarEmpleado = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTResultados2 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFidVehiculoOrden = new javax.swing.JTextField();
        jTFidClienteOrden1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFFecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFValor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFidEmpleadoOrden = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        setEnabled(false);
        setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Orden Alistamiento"));
        jPanel1.setLayout(null);

        jPanel2.setLayout(null);

        jTFModelo.setColumns(20);
        jPanel2.add(jTFModelo);
        jTFModelo.setBounds(90, 10, 270, 28);

        jLabel23.setText("Modelo");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(10, 20, 53, 18);

        jLabel22.setText("Linea");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(10, 50, 37, 18);

        jLabel21.setText("Marca");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(10, 80, 43, 18);

        jLabel20.setText("No. Chasis");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(10, 110, 71, 18);

        jLabel24.setText("Color");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(10, 140, 38, 18);

        jTFColor.setColumns(20);
        jPanel2.add(jTFColor);
        jTFColor.setBounds(90, 130, 270, 28);

        jTFNoChasis.setColumns(20);
        jPanel2.add(jTFNoChasis);
        jTFNoChasis.setBounds(90, 100, 270, 28);

        jTFMarca.setColumns(20);
        jPanel2.add(jTFMarca);
        jTFMarca.setBounds(90, 70, 270, 28);

        jTFLinea.setColumns(20);
        jPanel2.add(jTFLinea);
        jTFLinea.setBounds(90, 40, 270, 28);

        jTResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Chasis", "Linea", "Marca", "Color", "Modelo", "Cojineria", "Disponible"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTResultados);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 200, 550, 125);

        jBConsultarVehiculo.setText("Consultar");
        jPanel2.add(jBConsultarVehiculo);
        jBConsultarVehiculo.setBounds(380, 10, 90, 30);

        jLabel6.setText("Disponible");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 170, 73, 18);

        jCBDisponible.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "True" }));
        jCBDisponible.setEnabled(false);
        jPanel2.add(jCBDisponible);
        jCBDisponible.setBounds(90, 160, 120, 28);

        jTabbedPane1.addTab("Vehiculo", jPanel2);

        jPanel3.setLayout(null);

        jLabel16.setText("Identificacion");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(10, 20, 93, 18);

        jTFIdentificacion.setColumns(20);
        jPanel3.add(jTFIdentificacion);
        jTFIdentificacion.setBounds(160, 10, 190, 28);

        jTFNombre.setColumns(20);
        jPanel3.add(jTFNombre);
        jTFNombre.setBounds(160, 40, 190, 28);

        jLabel7.setText("Nombre");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 50, 57, 18);

        jTResultados1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Nombre", "Direccion", "Telefono", "Email", "Genero"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTResultados1);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(10, 80, 480, 125);

        jBConsultarCliente.setText("Consultar");
        jPanel3.add(jBConsultarCliente);
        jBConsultarCliente.setBounds(360, 10, 90, 30);

        jTabbedPane1.addTab("Cliente", jPanel3);

        jPanel5.setLayout(null);

        jLabel17.setText("Identificacion");
        jPanel5.add(jLabel17);
        jLabel17.setBounds(20, 20, 93, 18);

        jTFIdentificacion1.setColumns(20);
        jPanel5.add(jTFIdentificacion1);
        jTFIdentificacion1.setBounds(120, 10, 190, 28);

        jTFNombre1.setColumns(20);
        jPanel5.add(jTFNombre1);
        jTFNombre1.setBounds(120, 40, 190, 28);

        jLabel8.setText("Nombre");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(20, 50, 57, 18);

        jLabel25.setText("Cargo");
        jPanel5.add(jLabel25);
        jLabel25.setBounds(20, 80, 42, 18);

        jCBCargo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jefe de Taller" }));
        jCBCargo1.setEnabled(false);
        jCBCargo1.setName(""); // NOI18N
        jPanel5.add(jCBCargo1);
        jCBCargo1.setBounds(120, 70, 134, 28);

        jBConsultarEmpleado.setText("Consultar");
        jPanel5.add(jBConsultarEmpleado);
        jBConsultarEmpleado.setBounds(320, 10, 90, 30);

        jTResultados2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Nombre", "Direccion", "Telefono", "Email", "Genero", "Cargo", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTResultados2);

        jPanel5.add(jScrollPane3);
        jScrollPane3.setBounds(20, 110, 530, 125);

        jTabbedPane1.addTab("Empleado", jPanel5);

        jPanel4.setLayout(null);

        jLabel1.setText("Vehiculo Id");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(10, 30, 75, 18);

        jLabel2.setText("Cliente Id");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(320, 30, 65, 18);
        jPanel4.add(jTFidVehiculoOrden);
        jTFidVehiculoOrden.setBounds(100, 20, 140, 28);
        jPanel4.add(jTFidClienteOrden1);
        jTFidClienteOrden1.setBounds(390, 20, 140, 28);

        jLabel3.setText("Fecha");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(20, 90, 42, 18);
        jPanel4.add(jTFFecha);
        jTFFecha.setBounds(100, 80, 100, 28);

        jLabel4.setText("Valor");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(20, 120, 36, 18);
        jPanel4.add(jTFValor);
        jTFValor.setBounds(100, 110, 140, 28);

        jLabel5.setText("Empleado Id");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(295, 60, 90, 18);
        jPanel4.add(jTFidEmpleadoOrden);
        jTFidEmpleadoOrden.setBounds(390, 50, 140, 28);

        jLabel9.setText("Tipo Orden");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(299, 90, 80, 18);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Alistamiento", "Mantenimiento", "Reparacion" }));
        jPanel4.add(jComboBox1);
        jComboBox1.setBounds(390, 80, 140, 28);

        jTabbedPane1.addTab("Orden", jPanel4);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 20, 580, 370);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 610, 410);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConsultarCliente;
    private javax.swing.JButton jBConsultarEmpleado;
    private javax.swing.JButton jBConsultarVehiculo;
    private javax.swing.JComboBox jCBCargo1;
    private javax.swing.JComboBox jCBDisponible;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTFColor;
    private javax.swing.JTextField jTFFecha;
    private javax.swing.JTextField jTFIdentificacion;
    private javax.swing.JTextField jTFIdentificacion1;
    private javax.swing.JTextField jTFLinea;
    private javax.swing.JTextField jTFMarca;
    private javax.swing.JTextField jTFModelo;
    private javax.swing.JTextField jTFNoChasis;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFNombre1;
    private javax.swing.JTextField jTFValor;
    private javax.swing.JTextField jTFidClienteOrden1;
    private javax.swing.JTextField jTFidEmpleadoOrden;
    private javax.swing.JTextField jTFidVehiculoOrden;
    private javax.swing.JTable jTResultados;
    private javax.swing.JTable jTResultados1;
    private javax.swing.JTable jTResultados2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
