/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author juandapp
 */
public class JPOrdenes extends javax.swing.JPanel {

    /**
     * Creates new form JPOrdenes
     */
    public JPOrdenes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTFModelo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTFColor = new javax.swing.JTextField();
        jTFNoChasis = new javax.swing.JTextField();
        jTFMarca = new javax.swing.JTextField();
        jTFLinea = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTResultadosVehiculo = new javax.swing.JTable();
        jBConsultarVehiculo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jCBDisponible = new javax.swing.JComboBox();
        jBLimpiarVehiculo = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTFCodigoArticulo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTFNombreArticulo = new javax.swing.JTextField();
        jBConsultarArticulo = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTResultadosArticulo = new javax.swing.JTable();
        jBLimpiarArticulo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTFIdentificacionCliente = new javax.swing.JTextField();
        jTFNombreCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTResultadosCliente = new javax.swing.JTable();
        jBConsultarCliente = new javax.swing.JButton();
        jBLimpiarCliente = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTFIdentificacionEmpleado = new javax.swing.JTextField();
        jTFNombreEmpleado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jCBCargo1 = new javax.swing.JComboBox();
        jBConsultarEmpleado = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTResultados2 = new javax.swing.JTable();
        jBLimpiarempleado = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFidVehiculoOrden = new javax.swing.JTextField();
        jTFidClienteOrden1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFFecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFValor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFidEmpleadoOrden = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jCbTipoOrden = new javax.swing.JComboBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTPDescripcion = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTFidArticuloOrden = new javax.swing.JTextField();

        setEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Orden es de Trabajo"));
        jPanel1.setLayout(null);

        jPanel2.setLayout(null);

        jTFModelo.setColumns(20);
        jPanel2.add(jTFModelo);
        jTFModelo.setBounds(90, 10, 270, 28);

        jLabel23.setText("Modelo");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(10, 20, 53, 18);

        jLabel22.setText("Linea");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(10, 50, 37, 18);

        jLabel21.setText("Marca");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(10, 80, 43, 18);

        jLabel20.setText("No. Chasis");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(10, 110, 71, 18);

        jLabel24.setText("Color");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(10, 140, 38, 18);

        jTFColor.setColumns(20);
        jPanel2.add(jTFColor);
        jTFColor.setBounds(90, 130, 270, 28);

        jTFNoChasis.setColumns(20);
        jPanel2.add(jTFNoChasis);
        jTFNoChasis.setBounds(90, 100, 270, 28);

        jTFMarca.setColumns(20);
        jPanel2.add(jTFMarca);
        jTFMarca.setBounds(90, 70, 270, 28);

        jTFLinea.setColumns(20);
        jPanel2.add(jTFLinea);
        jTFLinea.setBounds(90, 40, 270, 28);

        jTResultadosVehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Chasis", "Linea", "Marca", "Color", "Modelo", "Cojineria", "Disponible"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTResultadosVehiculo);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 200, 550, 125);

        jBConsultarVehiculo.setText("Consultar");
        jPanel2.add(jBConsultarVehiculo);
        jBConsultarVehiculo.setBounds(380, 10, 90, 30);

        jLabel6.setText("Disponible");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 170, 73, 18);

        jCBDisponible.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "True", "False" }));
        jPanel2.add(jCBDisponible);
        jCBDisponible.setBounds(90, 160, 120, 28);

        jBLimpiarVehiculo.setText("Limpiar");
        jBLimpiarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarVehiculoActionPerformed(evt);
            }
        });
        jPanel2.add(jBLimpiarVehiculo);
        jBLimpiarVehiculo.setBounds(380, 50, 90, 30);

        jTabbedPane1.addTab("Vehiculo", jPanel2);

        jPanel6.setLayout(null);

        jLabel11.setText("Codigo");
        jPanel6.add(jLabel11);
        jLabel11.setBounds(10, 20, 49, 18);

        jTFCodigoArticulo.setColumns(20);
        jPanel6.add(jTFCodigoArticulo);
        jTFCodigoArticulo.setBounds(80, 10, 270, 28);

        jLabel12.setText("Nombre");
        jPanel6.add(jLabel12);
        jLabel12.setBounds(10, 50, 57, 18);

        jTFNombreArticulo.setColumns(20);
        jPanel6.add(jTFNombreArticulo);
        jTFNombreArticulo.setBounds(80, 40, 270, 28);

        jBConsultarArticulo.setText("Consultar");
        jPanel6.add(jBConsultarArticulo);
        jBConsultarArticulo.setBounds(380, 10, 90, 30);

        jTResultadosArticulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Cantidad", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTResultadosArticulo);

        jPanel6.add(jScrollPane5);
        jScrollPane5.setBounds(20, 80, 470, 125);

        jBLimpiarArticulo.setText("Limpiar");
        jBLimpiarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarArticuloActionPerformed(evt);
            }
        });
        jPanel6.add(jBLimpiarArticulo);
        jBLimpiarArticulo.setBounds(380, 40, 90, 30);

        jTabbedPane1.addTab("Articulo", jPanel6);

        jPanel3.setLayout(null);

        jLabel16.setText("Identificacion");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(10, 20, 93, 18);

        jTFIdentificacionCliente.setColumns(20);
        jPanel3.add(jTFIdentificacionCliente);
        jTFIdentificacionCliente.setBounds(160, 10, 190, 28);

        jTFNombreCliente.setColumns(20);
        jPanel3.add(jTFNombreCliente);
        jTFNombreCliente.setBounds(160, 40, 190, 28);

        jLabel7.setText("Nombre");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 50, 57, 18);

        jTResultadosCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Nombre", "Direccion", "Telefono", "Email", "Genero"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTResultadosCliente);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(10, 80, 480, 125);

        jBConsultarCliente.setText("Consultar");
        jPanel3.add(jBConsultarCliente);
        jBConsultarCliente.setBounds(360, 10, 90, 30);

        jBLimpiarCliente.setText("Limpiar");
        jBLimpiarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarClienteActionPerformed(evt);
            }
        });
        jPanel3.add(jBLimpiarCliente);
        jBLimpiarCliente.setBounds(360, 40, 90, 30);

        jTabbedPane1.addTab("Cliente", jPanel3);

        jPanel5.setLayout(null);

        jLabel17.setText("Identificacion");
        jPanel5.add(jLabel17);
        jLabel17.setBounds(20, 20, 93, 18);

        jTFIdentificacionEmpleado.setColumns(20);
        jPanel5.add(jTFIdentificacionEmpleado);
        jTFIdentificacionEmpleado.setBounds(120, 10, 190, 28);

        jTFNombreEmpleado.setColumns(20);
        jPanel5.add(jTFNombreEmpleado);
        jTFNombreEmpleado.setBounds(120, 40, 190, 28);

        jLabel8.setText("Nombre");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(20, 50, 57, 18);

        jLabel25.setText("Cargo");
        jPanel5.add(jLabel25);
        jLabel25.setBounds(20, 80, 42, 18);

        jCBCargo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jefe de Taller" }));
        jCBCargo1.setEnabled(false);
        jCBCargo1.setName(""); // NOI18N
        jPanel5.add(jCBCargo1);
        jCBCargo1.setBounds(120, 70, 134, 28);

        jBConsultarEmpleado.setText("Consultar");
        jPanel5.add(jBConsultarEmpleado);
        jBConsultarEmpleado.setBounds(320, 10, 90, 30);

        jTResultados2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Nombre", "Direccion", "Telefono", "Email", "Genero", "Cargo", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTResultados2);

        jPanel5.add(jScrollPane3);
        jScrollPane3.setBounds(20, 110, 530, 125);

        jBLimpiarempleado.setText("Limpiar");
        jBLimpiarempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarempleadoActionPerformed(evt);
            }
        });
        jPanel5.add(jBLimpiarempleado);
        jBLimpiarempleado.setBounds(320, 40, 90, 30);

        jTabbedPane1.addTab("Empleado", jPanel5);

        jPanel4.setLayout(null);

        jLabel1.setText("Vehiculo Id");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(10, 30, 75, 18);

        jLabel2.setText("Cliente Id");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(280, 30, 65, 18);

        jTFidVehiculoOrden.setEnabled(false);
        jPanel4.add(jTFidVehiculoOrden);
        jTFidVehiculoOrden.setBounds(100, 20, 140, 28);

        jTFidClienteOrden1.setEnabled(false);
        jPanel4.add(jTFidClienteOrden1);
        jTFidClienteOrden1.setBounds(360, 20, 140, 28);

        jLabel3.setText("Fecha");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(10, 100, 42, 18);
        jPanel4.add(jTFFecha);
        jTFFecha.setBounds(100, 90, 100, 28);

        jLabel4.setText("Valor");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(10, 130, 36, 18);
        jPanel4.add(jTFValor);
        jTFValor.setBounds(100, 120, 140, 28);

        jLabel5.setText("Empleado Id");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(10, 60, 90, 18);

        jTFidEmpleadoOrden.setEnabled(false);
        jPanel4.add(jTFidEmpleadoOrden);
        jTFidEmpleadoOrden.setBounds(100, 50, 140, 28);

        jLabel9.setText("Tipo Orden");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(10, 160, 80, 18);
        jPanel4.add(jSeparator1);
        jSeparator1.setBounds(0, 80, 570, 10);

        jCbTipoOrden.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Alistamiento", "Mantenimiento", "Reparacion" }));
        jPanel4.add(jCbTipoOrden);
        jCbTipoOrden.setBounds(100, 150, 140, 28);

        jScrollPane4.setViewportView(jTPDescripcion);

        jPanel4.add(jScrollPane4);
        jScrollPane4.setBounds(100, 180, 270, 72);

        jLabel10.setText("Descripcion");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(10, 180, 82, 18);

        jButton1.setText("Crear Orden");
        jPanel4.add(jButton1);
        jButton1.setBounds(410, 260, 130, 30);

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(190, 260, 100, 30);

        jLabel13.setText("Articulo Id");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(280, 60, 70, 18);

        jTFidArticuloOrden.setEnabled(false);
        jPanel4.add(jTFidArticuloOrden);
        jTFidArticuloOrden.setBounds(360, 50, 140, 28);

        jTabbedPane1.addTab("Orden", jPanel4);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 20, 580, 370);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBLimpiarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarVehiculoActionPerformed
        jTFModelo.setText("");
        jTFLinea.setText("");
        jTFMarca.setText("");
        jTFNoChasis.setText("");
        jTFColor.setText("");
        jCBDisponible.setSelectedIndex(0);
    }//GEN-LAST:event_jBLimpiarVehiculoActionPerformed

    private void jBLimpiarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarArticuloActionPerformed
        jTFCodigoArticulo.setText("");
        jTFNombreArticulo.setText("");
    }//GEN-LAST:event_jBLimpiarArticuloActionPerformed

    private void jBLimpiarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarClienteActionPerformed
        jTFIdentificacionCliente.setText("");
        jTFNombreCliente.setText("");
    }//GEN-LAST:event_jBLimpiarClienteActionPerformed

    private void jBLimpiarempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarempleadoActionPerformed
        jTFIdentificacionEmpleado.setText("");
        jTFNombreEmpleado.setText("");
    }//GEN-LAST:event_jBLimpiarempleadoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTFFecha.setText("");
        jTFValor.setText("");
        jCbTipoOrden.setSelectedIndex(0);
        jTPDescripcion.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConsultarArticulo;
    private javax.swing.JButton jBConsultarCliente;
    private javax.swing.JButton jBConsultarEmpleado;
    private javax.swing.JButton jBConsultarVehiculo;
    private javax.swing.JButton jBLimpiarArticulo;
    private javax.swing.JButton jBLimpiarCliente;
    private javax.swing.JButton jBLimpiarVehiculo;
    private javax.swing.JButton jBLimpiarempleado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jCBCargo1;
    private javax.swing.JComboBox jCBDisponible;
    private javax.swing.JComboBox jCbTipoOrden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTFCodigoArticulo;
    private javax.swing.JTextField jTFColor;
    private javax.swing.JTextField jTFFecha;
    private javax.swing.JTextField jTFIdentificacionCliente;
    private javax.swing.JTextField jTFIdentificacionEmpleado;
    private javax.swing.JTextField jTFLinea;
    private javax.swing.JTextField jTFMarca;
    private javax.swing.JTextField jTFModelo;
    private javax.swing.JTextField jTFNoChasis;
    private javax.swing.JTextField jTFNombreArticulo;
    private javax.swing.JTextField jTFNombreCliente;
    private javax.swing.JTextField jTFNombreEmpleado;
    private javax.swing.JTextField jTFValor;
    private javax.swing.JTextField jTFidArticuloOrden;
    private javax.swing.JTextField jTFidClienteOrden1;
    private javax.swing.JTextField jTFidEmpleadoOrden;
    private javax.swing.JTextField jTFidVehiculoOrden;
    private javax.swing.JTextPane jTPDescripcion;
    private javax.swing.JTable jTResultados2;
    private javax.swing.JTable jTResultadosArticulo;
    private javax.swing.JTable jTResultadosCliente;
    private javax.swing.JTable jTResultadosVehiculo;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
