/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Controlador.AccesorioControlador;
import Controlador.ClienteControlador;
import Controlador.EmpleadoControlador;
import Controlador.OrdenControlador;
import Controlador.VehiculoControlador;
import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import GeneradorReportes.Reportes;

import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import logica.Articulo;
import logica.Cliente;
import logica.Empleado;
import logica.Vehiculo;

/**
 *
 * @author juandapp
 */
public class JPOrdenes extends javax.swing.JPanel {

    /**
     * Creates new form JPOrdenes
     */
    VehiculoControlador controladorVehiculo;
    AccesorioControlador controladorAccesorio;
    ClienteControlador controladorCliente;
    EmpleadoControlador controladorEmpleado;
    OrdenControlador controladorOrden;
    Reportes reporte;

    public JPOrdenes() {
        initComponents();
        controladorVehiculo = new VehiculoControlador();
        controladorAccesorio = new AccesorioControlador();
        controladorCliente = new ClienteControlador();
        controladorEmpleado = new EmpleadoControlador();
        controladorOrden = new OrdenControlador();

        String strFecha = "2010-06-18";
        String[] fechaString = strFecha.split("-");
        java.sql.Date d = new java.sql.Date(Integer.parseInt(fechaString[0]) - 1900, Integer.parseInt(fechaString[1]), Integer.parseInt(fechaString[2]));
        System.out.println(d.toString());


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTFModelo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTFColor = new javax.swing.JTextField();
        jTFNoChasis = new javax.swing.JTextField();
        jTFMarca = new javax.swing.JTextField();
        jTFLinea = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTResultadosVehiculo = new javax.swing.JTable();
        jBConsultarVehiculo = new javax.swing.JButton();
        jBLimpiarVehiculo = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTFCodigoArticulo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTFNombreArticulo = new javax.swing.JTextField();
        jBConsultarArticulo = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTResultadosArticulo = new javax.swing.JTable();
        jBLimpiarArticulo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTFIdentificacionCliente = new javax.swing.JTextField();
        jTFNombreCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTResultadosCliente = new javax.swing.JTable();
        jBConsultarCliente = new javax.swing.JButton();
        jBLimpiarCliente = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTFIdentificacionEmpleado = new javax.swing.JTextField();
        jTFNombreEmpleado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jCBCargo1 = new javax.swing.JComboBox();
        jBConsultarEmpleado = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTResultadosEmpleado = new javax.swing.JTable();
        jBLimpiarempleado = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFidVehiculoOrden = new javax.swing.JTextField();
        jTFidClienteOrden = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFValor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFidEmpleadoOrden = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jCbTipoOrden = new javax.swing.JComboBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTPDescripcion = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        jBCrearOrden = new javax.swing.JButton();
        jBLimpiarOrden = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTFidArticuloOrden = new javax.swing.JTextField();
        jDCFecha3 = new com.toedter.calendar.JDateChooser();

        setEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Orden es de Trabajo"));
        jPanel1.setLayout(null);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFModelo.setColumns(20);
        jPanel2.add(jTFModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel23.setText("Modelo");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel22.setText("Linea");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel21.setText("Marca");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel20.setText("No. Chasis");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel24.setText("Color");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jTFColor.setColumns(20);
        jPanel2.add(jTFColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jTFNoChasis.setColumns(20);
        jPanel2.add(jTFNoChasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jTFMarca.setColumns(20);
        jPanel2.add(jTFMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jTFLinea.setColumns(20);
        jPanel2.add(jTFLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jTResultadosVehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Chasis", "Linea", "Marca", "Color", "Modelo", "Cojineria", "Disponible"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTResultadosVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTResultadosVehiculoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTResultadosVehiculo);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 550, 125));

        jBConsultarVehiculo.setText("Consultar");
        jBConsultarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarVehiculoActionPerformed(evt);
            }
        });
        jPanel2.add(jBConsultarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 90, -1));

        jBLimpiarVehiculo.setText("Limpiar");
        jBLimpiarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarVehiculoActionPerformed(evt);
            }
        });
        jPanel2.add(jBLimpiarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 90, -1));

        jTabbedPane1.addTab("Vehiculo", jPanel2);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("Codigo");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jTFCodigoArticulo.setColumns(20);
        jPanel6.add(jTFCodigoArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel12.setText("Nombre");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jTFNombreArticulo.setColumns(20);
        jPanel6.add(jTFNombreArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        jBConsultarArticulo.setText("Consultar");
        jBConsultarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarArticuloActionPerformed(evt);
            }
        });
        jPanel6.add(jBConsultarArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 90, -1));

        jTResultadosArticulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Cantidad", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTResultadosArticulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTResultadosArticuloMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTResultadosArticulo);

        jPanel6.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 470, 125));

        jBLimpiarArticulo.setText("Limpiar");
        jBLimpiarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarArticuloActionPerformed(evt);
            }
        });
        jPanel6.add(jBLimpiarArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 90, -1));

        jTabbedPane1.addTab("Articulo", jPanel6);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setText("Identificacion");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jTFIdentificacionCliente.setColumns(20);
        jPanel3.add(jTFIdentificacionCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 190, -1));

        jTFNombreCliente.setColumns(20);
        jPanel3.add(jTFNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 190, -1));

        jLabel7.setText("Nombre");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jTResultadosCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Nombre", "Direccion", "Telefono", "Email", "Genero"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTResultadosCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTResultadosClienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTResultadosCliente);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 480, 125));

        jBConsultarCliente.setText("Consultar");
        jBConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarClienteActionPerformed(evt);
            }
        });
        jPanel3.add(jBConsultarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 90, -1));

        jBLimpiarCliente.setText("Limpiar");
        jBLimpiarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarClienteActionPerformed(evt);
            }
        });
        jPanel3.add(jBLimpiarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 90, -1));

        jTabbedPane1.addTab("Cliente", jPanel3);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("Identificacion");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jTFIdentificacionEmpleado.setColumns(20);
        jPanel5.add(jTFIdentificacionEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 190, -1));

        jTFNombreEmpleado.setColumns(20);
        jPanel5.add(jTFNombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 190, -1));

        jLabel8.setText("Nombre");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel25.setText("Cargo");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jCBCargo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jefe de Taller" }));
        jCBCargo1.setEnabled(false);
        jCBCargo1.setName(""); // NOI18N
        jPanel5.add(jCBCargo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        jBConsultarEmpleado.setText("Consultar");
        jBConsultarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarEmpleadoActionPerformed(evt);
            }
        });
        jPanel5.add(jBConsultarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 90, -1));

        jTResultadosEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Nombre", "Direccion", "Telefono", "Email", "Genero", "Cargo", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTResultadosEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTResultadosEmpleadoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTResultadosEmpleado);

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 530, 125));

        jBLimpiarempleado.setText("Limpiar");
        jBLimpiarempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarempleadoActionPerformed(evt);
            }
        });
        jPanel5.add(jBLimpiarempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 90, -1));

        jTabbedPane1.addTab("Empleado", jPanel5);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Vehiculo Id");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel2.setText("Cliente Id");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jTFidVehiculoOrden.setEnabled(false);
        jPanel4.add(jTFidVehiculoOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 140, -1));

        jTFidClienteOrden.setEnabled(false);
        jPanel4.add(jTFidClienteOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 140, -1));

        jLabel3.setText("Fecha");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel4.setText("Valor");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        jPanel4.add(jTFValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 140, -1));

        jLabel5.setText("Empleado Id");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 90, -1));

        jTFidEmpleadoOrden.setEnabled(false);
        jPanel4.add(jTFidEmpleadoOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 140, -1));

        jLabel9.setText("Tipo Orden");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, -1));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 570, 10));

        jCbTipoOrden.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Alistamiento", "Mantenimiento", "Reparacion" }));
        jPanel4.add(jCbTipoOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 140, -1));

        jScrollPane4.setViewportView(jTPDescripcion);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 270, 72));

        jLabel10.setText("Descripcion");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jBCrearOrden.setText("Crear Orden");
        jBCrearOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearOrdenActionPerformed(evt);
            }
        });
        jPanel4.add(jBCrearOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 130, -1));

        jBLimpiarOrden.setText("Limpiar");
        jBLimpiarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarOrdenActionPerformed(evt);
            }
        });
        jPanel4.add(jBLimpiarOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 100, -1));

        jLabel13.setText("Articulo Id");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 70, -1));

        jTFidArticuloOrden.setEnabled(false);
        jPanel4.add(jTFidArticuloOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 140, -1));

        jDCFecha3.setDateFormatString("dd MMM yyyy");
        jPanel4.add(jDCFecha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 140, -1));

        jTabbedPane1.addTab("Orden", jPanel4);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 20, 580, 370);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBLimpiarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarVehiculoActionPerformed
        jTFModelo.setText("");
        jTFLinea.setText("");
        jTFMarca.setText("");
        jTFNoChasis.setText("");
        jTFColor.setText("");
        jBConsultarVehiculo.doClick();
    }//GEN-LAST:event_jBLimpiarVehiculoActionPerformed

    private void jBLimpiarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarArticuloActionPerformed
        jTFCodigoArticulo.setText("");
        jTFNombreArticulo.setText("");
        jBConsultarArticulo.doClick();
    }//GEN-LAST:event_jBLimpiarArticuloActionPerformed

    private void jBLimpiarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarClienteActionPerformed
        jTFIdentificacionCliente.setText("");
        jTFNombreCliente.setText("");
        jBConsultarCliente.doClick();
    }//GEN-LAST:event_jBLimpiarClienteActionPerformed

    private void jBLimpiarempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarempleadoActionPerformed
        jTFIdentificacionEmpleado.setText("");
        jTFNombreEmpleado.setText("");
        jBConsultarEmpleado.doClick();
    }//GEN-LAST:event_jBLimpiarempleadoActionPerformed

    private void jBLimpiarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarOrdenActionPerformed
        jTFidArticuloOrden.setText("");
        jTFidClienteOrden.setText("");
        jTFidEmpleadoOrden.setText("");
        jTFidVehiculoOrden.setText("");
        jDCFecha3.setDate(new java.util.Date());
        jTFValor.setText("");
        jCbTipoOrden.setSelectedIndex(0);
        jTPDescripcion.setText("");
    }//GEN-LAST:event_jBLimpiarOrdenActionPerformed

    private void jBConsultarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarVehiculoActionPerformed
        LinkedList consulta = new LinkedList();
        try {
            consulta = controladorVehiculo.consultar(jTFNoChasis.getText(), jTFMarca.getText(), jTFModelo.getText(), jTFLinea.getText(),
                    jTFColor.getText());
            Object[][] s = new Object[consulta.size()][7];
            for (int i = 0; i < consulta.size(); i++) {
                Vehiculo v = (Vehiculo) consulta.get(i);

                if (!v.getModelo_v().isEmpty()) {
                    s[i][0] = v.getNumerochasis_v();
                    s[i][1] = v.getLinea_v();
                    s[i][2] = v.getMarca_v();
                    s[i][3] = v.getColor_v();
                    s[i][4] = v.getModelo_v();
                    s[i][5] = v.getCojineria_v();
                    s[i][6] = v.getDisponible_v();
                } else {
                    s = null;
                }
            }
            TableModel myModel = new DefaultTableModel(s, new String[]{"No Chasis", "Linea", "Marca", "Color", "Modelo", "Cojineria", "Disponible"}) {

                boolean[] canEdit = new boolean[]{false, false, false, false, false, false, false
                };

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            };
            ///remover filas
            jTResultadosVehiculo.setModel(myModel);
            jTResultadosVehiculo.setRowSorter(new TableRowSorter(myModel));

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBConsultarVehiculoActionPerformed

    private void jTResultadosVehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTResultadosVehiculoMouseClicked
        int selectedRow = jTResultadosVehiculo.getSelectedRow();
        jTFidVehiculoOrden.setText("" + jTResultadosVehiculo.getModel().getValueAt(selectedRow, 0));
        JOptionPane.showMessageDialog(this, "Vehiculo Seleccionado", "Vehiculo Ordenes", JOptionPane.INFORMATION_MESSAGE);
        jTabbedPane1.setSelectedIndex(1);
        jBConsultarArticulo.doClick();
    }//GEN-LAST:event_jTResultadosVehiculoMouseClicked

    private void jBConsultarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarArticuloActionPerformed
        LinkedList consulta = new LinkedList();
        try {
            consulta = controladorAccesorio.consultar(jTFCodigoArticulo.getText(), jTFNombreArticulo.getText());
            Object[][] s = new Object[consulta.size()][4];
            for (int i = 0; i < consulta.size(); i++) {
                Articulo articulo = (Articulo) consulta.get(i);
                if (articulo.getNombre() != null) {
                    s[i][0] = articulo.getCodigo_a();
                    s[i][1] = articulo.getNombre();
                    s[i][2] = articulo.getDescripcion();
                    s[i][3] = articulo.getCantidad();
                } else {
                    s = null;
                }
            }
            TableModel myModel = new DefaultTableModel(s, new String[]{"Codigo", "Nombre", "Descripcion", "Cantidad"}) {

                boolean[] canEdit = new boolean[]{false, false, false, false
                };

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            };
            ///remover filas
            jTResultadosArticulo.setModel(myModel);
            jTResultadosArticulo.setRowSorter(new TableRowSorter(myModel));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBConsultarArticuloActionPerformed

    private void jTResultadosArticuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTResultadosArticuloMouseClicked
        int selectedRow = jTResultadosArticulo.getSelectedRow();
        jTFidArticuloOrden.setText("" + jTResultadosArticulo.getModel().getValueAt(selectedRow, 0));
        JOptionPane.showMessageDialog(this, "Articulo Seleccionado", "Articulo Ordenes", JOptionPane.INFORMATION_MESSAGE);
        jTabbedPane1.setSelectedIndex(2);
        jBConsultarCliente.doClick();
    }//GEN-LAST:event_jTResultadosArticuloMouseClicked

    private void jBConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarClienteActionPerformed
        LinkedList consulta = new LinkedList();
        try {
            consulta = controladorCliente.consultar(jTFIdentificacionCliente.getText(), jTFNombreCliente.getText());
            Object[][] s = new Object[consulta.size()][6];
            for (int i = 0; i < consulta.size(); i++) {
                Cliente cliente = (Cliente) consulta.get(i);
                if (cliente.getId_c().getNombre_p() != null) {
                    s[i][0] = cliente.getId_c().getId_p();
                    s[i][1] = cliente.getId_c().getNombre_p();
                    s[i][2] = cliente.getId_c().getDireccion_p();
                    s[i][3] = cliente.getId_c().getTelefono_p();
                    s[i][4] = cliente.getId_c().getEmail_p();
                    s[i][5] = cliente.getId_c().getGenero_p();
                } else {
                    s = null;
                }
            }
            TableModel myModel = new javax.swing.table.DefaultTableModel(s, new String[]{"Identificacion", "Nombre",
                        "Direccion", "Telefono", "Email", "Genero"}) {

                boolean[] canEdit = new boolean[]{false, false, false, false, false, false
                };

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            };
            ///remover filas
            jTResultadosCliente.setModel(myModel);
            jTResultadosCliente.setRowSorter(new TableRowSorter(myModel));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBConsultarClienteActionPerformed

    private void jTResultadosClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTResultadosClienteMouseClicked
        int selectedRow = jTResultadosCliente.getSelectedRow();
        jTFidClienteOrden.setText("" + jTResultadosCliente.getModel().getValueAt(selectedRow, 0));
        JOptionPane.showMessageDialog(this, "Cliente Seleccionado", "Cliente Ordenes", JOptionPane.INFORMATION_MESSAGE);
        jTabbedPane1.setSelectedIndex(3);
        jBConsultarEmpleado.doClick();
    }//GEN-LAST:event_jTResultadosClienteMouseClicked

    private void jBConsultarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarEmpleadoActionPerformed
        LinkedList consulta = new LinkedList();
        try {
            if (jCBCargo1.getSelectedItem().toString().equals("Seleccionar")) {
                consulta = controladorEmpleado.consultar(jTFIdentificacionEmpleado.getText(), jTFNombreCliente.getText(), "");
            } else {
                consulta = controladorEmpleado.consultar(jTFIdentificacionEmpleado.getText(), jTFNombreEmpleado.getText(), jCBCargo1.getSelectedItem().toString());
            }
            Object[][] s = new Object[consulta.size()][8];
            for (int i = 0; i < consulta.size(); i++) {
                Empleado empleado = (Empleado) consulta.get(i);
                if (empleado.getId_e().getNombre_p() != null) {
                    s[i][0] = empleado.getId_e().getId_p();
                    s[i][1] = empleado.getId_e().getNombre_p();
                    s[i][2] = empleado.getId_e().getDireccion_p();
                    s[i][3] = empleado.getId_e().getTelefono_p();
                    s[i][4] = empleado.getId_e().getEmail_p();
                    s[i][5] = empleado.getId_e().getGenero_p();
                    s[i][6] = empleado.getTipo_e();
                    s[i][7] = empleado.getContrasena_e();
                } else {
                    s = null;
                }
            }
            TableModel myModel = new javax.swing.table.DefaultTableModel(s, new String[]{"Identificacion", "Nombre",
                        "Direccion", "Telefono", "Email", "Genero", "Cargo", "Password"}) {

                boolean[] canEdit = new boolean[]{false, false, false, false, false, false, false, false
                };

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            };
            ///remover filas
            jTResultadosEmpleado.setModel(myModel);
            jTResultadosEmpleado.setRowSorter(new TableRowSorter(myModel));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBConsultarEmpleadoActionPerformed

    private void jTResultadosEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTResultadosEmpleadoMouseClicked
        int selectedRow = jTResultadosEmpleado.getSelectedRow();
        jTFidEmpleadoOrden.setText("" + jTResultadosEmpleado.getModel().getValueAt(selectedRow, 0));
        JOptionPane.showMessageDialog(this, "Empleado Seleccionado", "Empleado Ordenes", JOptionPane.INFORMATION_MESSAGE);
        jTabbedPane1.setSelectedIndex(4);

    }//GEN-LAST:event_jTResultadosEmpleadoMouseClicked

    private void jBCrearOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearOrdenActionPerformed
        int guardar = -1;
        try {

            java.sql.Date fecha=new java.sql.Date(jDCFecha3.getDate().getTime());   
         /*   String[] fechaString = jTFFecha.getText().split("/");
            java.sql.Date d = new java.sql.Date(Integer.parseInt(fechaString[0]) - 1901, Integer.parseInt(fechaString[1]) + 11, Integer.parseInt(fechaString[2]));
            System.out.println(d.toString());*/

            Integer.parseInt(jTFidEmpleadoOrden.getText()); 
            Integer.parseInt(jTFidClienteOrden.getText());
            Integer.parseInt(jTFidVehiculoOrden.getText());
            Integer.parseInt(jTFidArticuloOrden.getText());
            Integer.parseInt(jTFValor.getText());

            guardar = controladorOrden.guardar(
                    Integer.parseInt(jTFidEmpleadoOrden.getText()),
                    Integer.parseInt(jTFidClienteOrden.getText()),
                    Integer.parseInt(jTFidVehiculoOrden.getText()),
                    Integer.parseInt(jTFidArticuloOrden.getText()),
                    Integer.parseInt(jTFValor.getText()),
                    fecha,
                    jCbTipoOrden.getSelectedItem().toString(),
                    jTPDescripcion.getText());

        } catch (Exception e) {
            e.printStackTrace();
            System.out.println();
        }

        if (guardar == -1) {
            JOptionPane.showMessageDialog(this, "No su pudo crear la Orden", "Error Base Datos", JOptionPane.ERROR_MESSAGE);
        } else {
            reporte= new Reportes();
            reporte.generarReporte("reporteOrdenRegistrada");
            JOptionPane.showMessageDialog(this, "Orden Creada correctamente", "Base Datos", JOptionPane.INFORMATION_MESSAGE);
            
        }
    }//GEN-LAST:event_jBCrearOrdenActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConsultarArticulo;
    private javax.swing.JButton jBConsultarCliente;
    private javax.swing.JButton jBConsultarEmpleado;
    private javax.swing.JButton jBConsultarVehiculo;
    private javax.swing.JButton jBCrearOrden;
    private javax.swing.JButton jBLimpiarArticulo;
    private javax.swing.JButton jBLimpiarCliente;
    private javax.swing.JButton jBLimpiarOrden;
    private javax.swing.JButton jBLimpiarVehiculo;
    private javax.swing.JButton jBLimpiarempleado;
    private javax.swing.JComboBox jCBCargo1;
    private javax.swing.JComboBox jCbTipoOrden;
    private com.toedter.calendar.JDateChooser jDCFecha3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTFCodigoArticulo;
    private javax.swing.JTextField jTFColor;
    private javax.swing.JTextField jTFIdentificacionCliente;
    private javax.swing.JTextField jTFIdentificacionEmpleado;
    private javax.swing.JTextField jTFLinea;
    private javax.swing.JTextField jTFMarca;
    private javax.swing.JTextField jTFModelo;
    private javax.swing.JTextField jTFNoChasis;
    private javax.swing.JTextField jTFNombreArticulo;
    private javax.swing.JTextField jTFNombreCliente;
    private javax.swing.JTextField jTFNombreEmpleado;
    private javax.swing.JTextField jTFValor;
    private javax.swing.JTextField jTFidArticuloOrden;
    private javax.swing.JTextField jTFidClienteOrden;
    private javax.swing.JTextField jTFidEmpleadoOrden;
    private javax.swing.JTextField jTFidVehiculoOrden;
    private javax.swing.JTextPane jTPDescripcion;
    private javax.swing.JTable jTResultadosArticulo;
    private javax.swing.JTable jTResultadosCliente;
    private javax.swing.JTable jTResultadosEmpleado;
    private javax.swing.JTable jTResultadosVehiculo;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
