/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author juandapp
 */
public class JPReporte extends javax.swing.JPanel {

    /**
     * Creates new form JPReporte
     */
    public JPReporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCotizacion = new javax.swing.JPanel();
        jBLimpiar = new javax.swing.JButton();
        jBGenerar = new javax.swing.JButton();
        jBLimpiar1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jPanelCotizacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Reporte"));
        jPanelCotizacion.setLayout(null);

        jBLimpiar.setText("Ventas");
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });
        jPanelCotizacion.add(jBLimpiar);
        jBLimpiar.setBounds(320, 170, 100, 30);

        jBGenerar.setText("Clientes");
        jBGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGenerarActionPerformed(evt);
            }
        });
        jPanelCotizacion.add(jBGenerar);
        jBGenerar.setBounds(320, 50, 100, 33);

        jBLimpiar1.setText("Empleados");
        jBLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiar1ActionPerformed(evt);
            }
        });
        jPanelCotizacion.add(jBLimpiar1);
        jBLimpiar1.setBounds(320, 110, 100, 30);

        jLabel2.setText("Lista los empleados de la compañia");
        jPanelCotizacion.add(jLabel2);
        jLabel2.setBounds(10, 110, 250, 20);

        jLabel3.setText("Lista los clientes de la compañia");
        jPanelCotizacion.add(jLabel3);
        jLabel3.setBounds(10, 60, 220, 17);

        jLabel4.setText("Lista las ventas registradas");
        jPanelCotizacion.add(jLabel4);
        jLabel4.setBounds(10, 170, 220, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jBGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGenerarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBGenerarActionPerformed

    private void jBLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBLimpiar1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGenerar;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JButton jBLimpiar1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelCotizacion;
    // End of variables declaration//GEN-END:variables
}
