/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import GeneradorReportes.Reportes;

/**
 *
 * @author juandapp
 */
public class JPReporte extends javax.swing.JPanel {

    /**
     * Creates new form JPReporte
     * 
     */
    Reportes reporte;
    public JPReporte() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCotizacion = new javax.swing.JPanel();
        jBVentas = new javax.swing.JButton();
        jBClientes = new javax.swing.JButton();
        jBEmpleados = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jPanelCotizacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Reporte"));
        jPanelCotizacion.setLayout(null);

        jBVentas.setText("Ventas");
        jBVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVentasActionPerformed(evt);
            }
        });
        jPanelCotizacion.add(jBVentas);
        jBVentas.setBounds(320, 170, 100, 30);

        jBClientes.setText("Clientes");
        jBClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBClientesActionPerformed(evt);
            }
        });
        jPanelCotizacion.add(jBClientes);
        jBClientes.setBounds(320, 50, 100, 33);

        jBEmpleados.setText("Empleados");
        jBEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEmpleadosActionPerformed(evt);
            }
        });
        jPanelCotizacion.add(jBEmpleados);
        jBEmpleados.setBounds(320, 110, 130, 30);

        jLabel2.setText("Lista los empleados de la compañia");
        jPanelCotizacion.add(jLabel2);
        jLabel2.setBounds(10, 110, 310, 20);

        jLabel3.setText("Lista los clientes de la compañia");
        jPanelCotizacion.add(jLabel3);
        jLabel3.setBounds(10, 60, 300, 17);

        jLabel4.setText("Lista las ventas registradas");
        jPanelCotizacion.add(jLabel4);
        jLabel4.setBounds(10, 170, 310, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVentasActionPerformed
// TODO add your handling code here:
        reporte= new Reportes();
        reporte.generarReporte("reporteVentas");
    }//GEN-LAST:event_jBVentasActionPerformed

    private void jBClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBClientesActionPerformed
        // TODO add your handling code here:
        reporte= new Reportes();
        reporte.generarReporte("reporteClientes");
    }//GEN-LAST:event_jBClientesActionPerformed

    private void jBEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEmpleadosActionPerformed
        // TODO add your handling code here:
        reporte= new Reportes();
        reporte.generarReporte("reporteUsuarios");
    }//GEN-LAST:event_jBEmpleadosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBClientes;
    private javax.swing.JButton jBEmpleados;
    private javax.swing.JButton jBVentas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelCotizacion;
    // End of variables declaration//GEN-END:variables
}
