/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Controlador.EmpleadoControlador;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import logica.Cliente;
import logica.Empleado;

/**
 *
 * @author juandapp
 */
public class JPUsuario extends javax.swing.JPanel {

    /**
     * Creates new form JPCliente
     */
    EmpleadoControlador controladorEmpleado;

    public JPUsuario() {
        initComponents();
        controladorEmpleado = new EmpleadoControlador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCBGenero = new javax.swing.JComboBox();
        jTFFechaNacimiento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTFDireccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jCBCargo = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jTFIdentificacion = new javax.swing.JTextField();
        jPFPassword = new javax.swing.JPasswordField();
        jLabel21 = new javax.swing.JLabel();
        jBLimpiar = new javax.swing.JButton();
        jBCrear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTFIdentificacion1 = new javax.swing.JTextField();
        jBConsultar = new javax.swing.JButton();
        jTFNombre1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTResultados = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jCBCargo1 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jTFNombre3 = new javax.swing.JTextField();
        jCBGenero2 = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTFFechaNacimiento2 = new javax.swing.JTextField();
        jTFTelefono2 = new javax.swing.JTextField();
        jTFDireccion2 = new javax.swing.JTextField();
        jTFEmail2 = new javax.swing.JTextField();
        jCBCargo2 = new javax.swing.JComboBox();
        jTFIdentificacion3 = new javax.swing.JTextField();
        jPFPassword1 = new javax.swing.JPasswordField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jBModificar = new javax.swing.JButton();

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));
        jPanel5.setLayout(null);
        jPanel5.add(jLabel13);
        jLabel13.setBounds(18, 182, 0, 0);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jTFNombre.setColumns(20);
        jPanel1.add(jTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel4.setText("Telefono");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel3.setText("Genero");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jCBGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Femenino", "Masculino" }));
        jCBGenero.setName(""); // NOI18N
        jPanel1.add(jCBGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        jTFFechaNacimiento.setColumns(20);
        jPanel1.add(jTFFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        jLabel5.setText("Fecha de nacimiento");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jTFTelefono.setColumns(20);
        jPanel1.add(jTFTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 131, -1, -1));

        jTFDireccion.setColumns(20);
        jPanel1.add(jTFDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        jLabel8.setText("Direccion");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jTFEmail.setColumns(20);
        jPanel1.add(jTFEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        jLabel9.setText("Email");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel15.setText("Cargo");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jCBCargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Gerente", "Jefe de Taller", "Vendedor" }));
        jCBCargo.setName(""); // NOI18N
        jPanel1.add(jCBCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        jLabel20.setText("Identificacion");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jTFIdentificacion.setColumns(20);
        jPanel1.add(jTFIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));
        jPanel1.add(jPFPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 160, -1));

        jLabel21.setText("Password");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jBLimpiar.setText("Limpiar");
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(jBLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 80, -1));

        jBCrear.setText("Crear");
        jBCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearActionPerformed(evt);
            }
        });
        jPanel1.add(jBCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 100, -1));

        jTabbedPane1.addTab("Crear", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setText("Identificacion");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jTFIdentificacion1.setColumns(20);
        jPanel2.add(jTFIdentificacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 190, -1));

        jBConsultar.setText("Consultar");
        jBConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarActionPerformed(evt);
            }
        });
        jPanel2.add(jBConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 90, -1));

        jTFNombre1.setColumns(20);
        jPanel2.add(jTFNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 190, -1));

        jLabel6.setText("Nombre");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jTResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Nombre", "Direccion", "Telefono", "Email", "Genero", "Cargo", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTResultados);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 530, 125));

        jLabel22.setText("Cargo");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jCBCargo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Gerente", "Jefe de Taller", "Vendedor" }));
        jCBCargo1.setName(""); // NOI18N
        jPanel2.add(jCBCargo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        jTabbedPane1.addTab("Consultar", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setText("Nombre");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jTFNombre3.setColumns(20);
        jPanel3.add(jTFNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jCBGenero2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Femenino", "Masculino" }));
        jCBGenero2.setName(""); // NOI18N
        jPanel3.add(jCBGenero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        jLabel24.setText("Genero");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel25.setText("Fecha de nacimiento");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jTFFechaNacimiento2.setColumns(20);
        jPanel3.add(jTFFechaNacimiento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        jTFTelefono2.setColumns(20);
        jPanel3.add(jTFTelefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        jTFDireccion2.setColumns(20);
        jPanel3.add(jTFDireccion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        jTFEmail2.setColumns(20);
        jPanel3.add(jTFEmail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        jCBCargo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Gerente", "Jefe de Taller", "Vendedor" }));
        jCBCargo2.setName(""); // NOI18N
        jPanel3.add(jCBCargo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        jTFIdentificacion3.setColumns(20);
        jPanel3.add(jTFIdentificacion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));
        jPanel3.add(jPFPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 130, -1));

        jLabel26.setText("Password");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel27.setText("Identificacion");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel28.setText("Cargo");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel29.setText("Email");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel30.setText("Direccion");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel31.setText("Telefono");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jBModificar.setText("Modificar");
        jPanel3.add(jBModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 100, -1));

        jTabbedPane1.addTab("Modificar", jPanel3);

        jPanel4.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 565, 386));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        limpiarCamposCrear();
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jBCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearActionPerformed
        int guardar = -1;
        try {
            Integer.parseInt(jTFIdentificacion.getText());
            Integer.parseInt(jTFTelefono.getText());
            guardar = controladorEmpleado.guardar(
                    Integer.parseInt(jTFIdentificacion.getText()),
                    jTFNombre.getText(),
                    jTFDireccion.getText(),
                    jTFTelefono.getText(),
                    jTFEmail.getText(),
                    jCBGenero.getSelectedItem().toString(),
                    jCBCargo.getSelectedItem().toString(),
                    jPFPassword.getPassword().toString());
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println();
        }

        if (guardar == -1) {
            JOptionPane.showMessageDialog(this, "No su pudo crear el Usuario", "Error Base Datos", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Usuario Creado correctamente", "Base Datos", JOptionPane.INFORMATION_MESSAGE);
            jTFIdentificacion1.setText(jTFIdentificacion.getText());
            jBConsultar.doClick();
            jTabbedPane1.setSelectedIndex(1);
            limpiarCamposCrear();
            
        }
    }//GEN-LAST:event_jBCrearActionPerformed

    private void jBConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarActionPerformed
        LinkedList consulta = new LinkedList();
        System.out.println("ya se consulto  "+consulta );
        try {
            
            consulta = controladorEmpleado.consultar(jTFIdentificacion1.getText(), jTFNombre1.getText(), jCBGenero2.getSelectedItem().toString());
            
            Object[][] s = new Object[consulta.size()][8];
            for (int i = 0; i < consulta.size(); i++) {
                Empleado empleado = (Empleado) consulta.get(i);
                if (empleado.getId_e().getNombre_p() != null) {
                    s[i][0] = empleado.getId_e().getId_p();
                    s[i][1] = empleado.getId_e().getNombre_p();
                    s[i][2] = empleado.getId_e().getDireccion_p();
                    s[i][3] = empleado.getId_e().getTelefono_p();
                    s[i][4] = empleado.getId_e().getEmail_p();
                    s[i][5] = empleado.getId_e().getGenero_p();
                    s[i][6] = empleado.getTipo_e();
                    s[i][7] = empleado.getContrasena_e();
                } else {
                    s = null;
                }
            }
            TableModel myModel = new javax.swing.table.DefaultTableModel(s, new String[]{"Identificacion", "Nombre",
                        "Direccion", "Telefono", "Email", "Genero","Cargo", "Password"}) {

                boolean[] canEdit = new boolean[]{false, false, false, false,false, false, false, false
                };

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            };
            ///remover filas
            jTResultados.setModel(myModel);            
            jTResultados.setRowSorter(new TableRowSorter(myModel));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBConsultarActionPerformed

    private void limpiarCamposModificar() {
        jTFDireccion2.setText("");
        jTFEmail2.setText("");
        jTFFechaNacimiento2.setText("");
        jTFIdentificacion3.setText("");
        jTFNombre3.setText("");
        jTFTelefono2.setText("");
        jCBGenero2.setSelectedIndex(0);
        jCBCargo2.setSelectedIndex(0);
        jPFPassword1.setText("");
    }

    private void limpiarCamposCrear() {
        jTFDireccion.setText("");
        jTFEmail.setText("");
        jTFFechaNacimiento.setText("");
        jTFIdentificacion.setText("");
        jTFNombre.setText("");
        jTFTelefono.setText("");
        jCBGenero.setSelectedIndex(0);
        jCBCargo.setSelectedIndex(0);
        jPFPassword.setText("");
    }

    private void limpiarCamposConsultar() {
        jTFIdentificacion1.setText("");
        jTFNombre1.setText("");
        jCBCargo1.setSelectedIndex(0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConsultar;
    private javax.swing.JButton jBCrear;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JComboBox jCBCargo;
    private javax.swing.JComboBox jCBCargo1;
    private javax.swing.JComboBox jCBCargo2;
    private javax.swing.JComboBox jCBGenero;
    private javax.swing.JComboBox jCBGenero2;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPFPassword;
    private javax.swing.JPasswordField jPFPassword1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFDireccion;
    private javax.swing.JTextField jTFDireccion2;
    private javax.swing.JTextField jTFEmail;
    private javax.swing.JTextField jTFEmail2;
    private javax.swing.JTextField jTFFechaNacimiento;
    private javax.swing.JTextField jTFFechaNacimiento2;
    private javax.swing.JTextField jTFIdentificacion;
    private javax.swing.JTextField jTFIdentificacion1;
    private javax.swing.JTextField jTFIdentificacion3;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFNombre1;
    private javax.swing.JTextField jTFNombre3;
    private javax.swing.JTextField jTFTelefono;
    private javax.swing.JTextField jTFTelefono2;
    private javax.swing.JTable jTResultados;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
