/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Controlador.C_compra_VControlador;
import Controlador.ClienteControlador;
import Controlador.VehiculoControlador;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import logica.Cliente;
import logica.Vehiculo;
import GeneradorReportes.Reportes;

/**
 *
 * @author juandapp
 */
public class JPVenta extends javax.swing.JPanel {

    /**
     * Creates new form JPCliente
     */
    VehiculoControlador vehiculoControlador;
    ClienteControlador controladorCliente;
    C_compra_VControlador ventaControlador;
    Reportes reporte;

    public JPVenta() {
        initComponents();
        vehiculoControlador = new VehiculoControlador();
        controladorCliente = new ClienteControlador();
        ventaControlador = new C_compra_VControlador();
        
        jBConsultarVehiculo.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTFModelo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTFColor = new javax.swing.JTextField();
        jTFNoChasis = new javax.swing.JTextField();
        jTFMarca = new javax.swing.JTextField();
        jTFLinea = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTResultadosVehiculo = new javax.swing.JTable();
        jBConsultarVehiculo = new javax.swing.JButton();
        jBLimpiarVehiculo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTFIdentificacionCliente = new javax.swing.JTextField();
        jTFNombreCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTResultadosCliente = new javax.swing.JTable();
        jBConsultarCliente = new javax.swing.JButton();
        jBLimpiarCliente = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFidVehiculoOrden = new javax.swing.JTextField();
        jTFidClienteOrden = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFFecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFValor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jCbTipoPago = new javax.swing.JComboBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTPDescripcion = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        jBCrearOrden = new javax.swing.JButton();
        jBLimpiarOrden = new javax.swing.JButton();

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));
        jPanel5.setLayout(null);
        jPanel5.add(jLabel13);
        jLabel13.setBounds(18, 182, 0, 0);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Vehiculo"));
        jPanel4.setLayout(null);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFModelo.setColumns(20);
        jPanel2.add(jTFModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel23.setText("Modelo");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel22.setText("Linea");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel21.setText("Marca");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel20.setText("No. Chasis");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel24.setText("Color");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jTFColor.setColumns(20);
        jPanel2.add(jTFColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jTFNoChasis.setColumns(20);
        jPanel2.add(jTFNoChasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jTFMarca.setColumns(20);
        jPanel2.add(jTFMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jTFLinea.setColumns(20);
        jPanel2.add(jTFLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jTResultadosVehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Chasis", "Linea", "Marca", "Color", "Modelo", "Cojineria", "Disponible"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTResultadosVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTResultadosVehiculoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTResultadosVehiculo);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 550, 125));

        jBConsultarVehiculo.setText("Consultar");
        jBConsultarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarVehiculoActionPerformed(evt);
            }
        });
        jPanel2.add(jBConsultarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 90, -1));

        jBLimpiarVehiculo.setText("Limpiar");
        jBLimpiarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarVehiculoActionPerformed(evt);
            }
        });
        jPanel2.add(jBLimpiarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 90, -1));

        jTabbedPane1.addTab("Vehiculo", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setText("Identificacion");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jTFIdentificacionCliente.setColumns(20);
        jPanel3.add(jTFIdentificacionCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 190, -1));

        jTFNombreCliente.setColumns(20);
        jPanel3.add(jTFNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 190, -1));

        jLabel7.setText("Nombre");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jTResultadosCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Nombre", "Direccion", "Telefono", "Email", "Genero"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTResultadosCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTResultadosClienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTResultadosCliente);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 480, 125));

        jBConsultarCliente.setText("Consultar");
        jBConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarClienteActionPerformed(evt);
            }
        });
        jPanel3.add(jBConsultarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 90, -1));

        jBLimpiarCliente.setText("Limpiar");
        jBLimpiarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarClienteActionPerformed(evt);
            }
        });
        jPanel3.add(jBLimpiarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 90, -1));

        jTabbedPane1.addTab("Cliente", jPanel3);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Vehiculo Id");
        jPanel8.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setText("Cliente Id");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jTFidVehiculoOrden.setEnabled(false);
        jPanel8.add(jTFidVehiculoOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 140, -1));

        jTFidClienteOrden.setEnabled(false);
        jPanel8.add(jTFidClienteOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 140, -1));

        jLabel3.setText("Fecha");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        jPanel8.add(jTFFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 100, -1));

        jLabel4.setText("Valor");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        jPanel8.add(jTFValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 140, -1));

        jLabel9.setText("Tipo Pago");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 60, -1));
        jPanel8.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 570, 10));

        jCbTipoPago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Efectivo", "Tarjeta" }));
        jPanel8.add(jCbTipoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 140, -1));

        jScrollPane4.setViewportView(jTPDescripcion);

        jPanel8.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 270, 72));

        jLabel10.setText("Descripcion");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jBCrearOrden.setText("Crear Venta");
        jBCrearOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearOrdenActionPerformed(evt);
            }
        });
        jPanel8.add(jBCrearOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 130, -1));

        jBLimpiarOrden.setText("Limpiar");
        jBLimpiarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarOrdenActionPerformed(evt);
            }
        });
        jPanel8.add(jBLimpiarOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 100, -1));

        jTabbedPane1.addTab("Orden", jPanel8);

        jPanel4.add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 20, 580, 370);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBLimpiarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarOrdenActionPerformed
        jTFidClienteOrden.setText("");
        jTFidVehiculoOrden.setText("");
        jTFFecha.setText("");
        jTFValor.setText("");
        jCbTipoPago.setSelectedIndex(0);
        jTPDescripcion.setText("");
    }//GEN-LAST:event_jBLimpiarOrdenActionPerformed

    private void jBCrearOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearOrdenActionPerformed
        int guardar = -1;
        try {

            String[] fechaString = jTFFecha.getText().split("/");
            java.sql.Date d = new java.sql.Date(Integer.parseInt(fechaString[0]) - 1901, Integer.parseInt(fechaString[1]) + 11, Integer.parseInt(fechaString[2]));
            System.out.println(d.toString());

            Integer.parseInt(jTFidClienteOrden.getText());
            Integer.parseInt(jTFidVehiculoOrden.getText());
            Integer.parseInt(jTFValor.getText());

            guardar = ventaControlador.guardar(
                    Integer.parseInt(jTFidClienteOrden.getText()),
                    Integer.parseInt(jTFidVehiculoOrden.getText()),
                    jCbTipoPago.getSelectedItem().toString());

        } catch (Exception e) {
            e.printStackTrace();
            System.out.println();
        }

        if (guardar == -1) {
            JOptionPane.showMessageDialog(this, "No su pudo crear la Orden", "Error Base Datos", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Orden Creada correctamente", "Base Datos", JOptionPane.INFORMATION_MESSAGE);
            reporte= new Reportes();
            reporte.generarReporte("reporteVentaRegistrada");
        }
    }//GEN-LAST:event_jBCrearOrdenActionPerformed

    private void jBLimpiarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarClienteActionPerformed
        jTFIdentificacionCliente.setText("");
        jTFNombreCliente.setText("");
        jBConsultarCliente.doClick();
    }//GEN-LAST:event_jBLimpiarClienteActionPerformed

    private void jBConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarClienteActionPerformed
        LinkedList consulta = new LinkedList();
        try {
            consulta = controladorCliente.consultar(jTFIdentificacionCliente.getText(), jTFNombreCliente.getText());
            Object[][] s = new Object[consulta.size()][6];
            for (int i = 0; i < consulta.size(); i++) {
                Cliente cliente = (Cliente) consulta.get(i);
                if (cliente.getId_c().getNombre_p() != null) {
                    s[i][0] = cliente.getId_c().getId_p();
                    s[i][1] = cliente.getId_c().getNombre_p();
                    s[i][2] = cliente.getId_c().getDireccion_p();
                    s[i][3] = cliente.getId_c().getTelefono_p();
                    s[i][4] = cliente.getId_c().getEmail_p();
                    s[i][5] = cliente.getId_c().getGenero_p();
                } else {
                    s = null;
                }
            }
            TableModel myModel = new javax.swing.table.DefaultTableModel(s, new String[]{"Identificacion", "Nombre",
                        "Direccion", "Telefono", "Email", "Genero"}) {

                boolean[] canEdit = new boolean[]{false, false, false, false, false, false
                };

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            };
            ///remover filas
            jTResultadosCliente.setModel(myModel);
            jTResultadosCliente.setRowSorter(new TableRowSorter(myModel));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBConsultarClienteActionPerformed

    private void jTResultadosClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTResultadosClienteMouseClicked
        int selectedRow = jTResultadosCliente.getSelectedRow();
        jTFidClienteOrden.setText("" + jTResultadosCliente.getModel().getValueAt(selectedRow, 0));
        JOptionPane.showMessageDialog(this, "Cliente Seleccionado", "Cliente Ordenes", JOptionPane.INFORMATION_MESSAGE);
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jTResultadosClienteMouseClicked

    private void jBLimpiarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarVehiculoActionPerformed
        jTFModelo.setText("");
        jTFLinea.setText("");
        jTFMarca.setText("");
        jTFNoChasis.setText("");
        jTFColor.setText("");
        jBConsultarVehiculo.doClick();
    }//GEN-LAST:event_jBLimpiarVehiculoActionPerformed

    private void jBConsultarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarVehiculoActionPerformed
        LinkedList consulta = new LinkedList();
        try {
            consulta = vehiculoControlador.consultar(jTFNoChasis.getText(), jTFMarca.getText(), jTFModelo.getText(), jTFLinea.getText(),
                    jTFColor.getText());
            Object[][] s = new Object[consulta.size()][7];
            for (int i = 0; i < consulta.size(); i++) {
                Vehiculo v = (Vehiculo) consulta.get(i);

                if (!v.getModelo_v().isEmpty()) {
                    s[i][0] = v.getNumerochasis_v();
                    s[i][1] = v.getLinea_v();
                    s[i][2] = v.getMarca_v();
                    s[i][3] = v.getColor_v();
                    s[i][4] = v.getModelo_v();
                    s[i][5] = v.getCojineria_v();
                    s[i][6] = v.getDisponible_v();
                } else {
                    s = null;
                }
            }
            TableModel myModel = new DefaultTableModel(s, new String[]{"No Chasis", "Linea", "Marca", "Color", "Modelo", "Cojineria", "Disponible"}) {

                boolean[] canEdit = new boolean[]{false, false, false, false, false, false, false
                };

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            };
            ///remover filas
            jTResultadosVehiculo.setModel(myModel);
            jTResultadosVehiculo.setRowSorter(new TableRowSorter(myModel));

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBConsultarVehiculoActionPerformed

    private void jTResultadosVehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTResultadosVehiculoMouseClicked
        int selectedRow = jTResultadosVehiculo.getSelectedRow();
        jTFidVehiculoOrden.setText("" + jTResultadosVehiculo.getModel().getValueAt(selectedRow, 0));
        JOptionPane.showMessageDialog(this, "Vehiculo Seleccionado", "Vehiculo Ordenes", JOptionPane.INFORMATION_MESSAGE);
        jTabbedPane1.setSelectedIndex(1);        
        jBConsultarCliente.doClick();
    }//GEN-LAST:event_jTResultadosVehiculoMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConsultarCliente;
    private javax.swing.JButton jBConsultarVehiculo;
    private javax.swing.JButton jBCrearOrden;
    private javax.swing.JButton jBLimpiarCliente;
    private javax.swing.JButton jBLimpiarOrden;
    private javax.swing.JButton jBLimpiarVehiculo;
    private javax.swing.JComboBox jCbTipoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTFColor;
    private javax.swing.JTextField jTFFecha;
    private javax.swing.JTextField jTFIdentificacionCliente;
    private javax.swing.JTextField jTFLinea;
    private javax.swing.JTextField jTFMarca;
    private javax.swing.JTextField jTFModelo;
    private javax.swing.JTextField jTFNoChasis;
    private javax.swing.JTextField jTFNombreCliente;
    private javax.swing.JTextField jTFValor;
    private javax.swing.JTextField jTFidClienteOrden;
    private javax.swing.JTextField jTFidVehiculoOrden;
    private javax.swing.JTextPane jTPDescripcion;
    private javax.swing.JTable jTResultadosCliente;
    private javax.swing.JTable jTResultadosVehiculo;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
