/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Controlador.VehiculoControlador;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import logica.Vehiculo;

/**
 *
 * @author juandapp
 */
public class JPVehiculo extends javax.swing.JPanel {

    /**
     * Creates new form JPCliente
     */
    VehiculoControlador vehiculoControlador;

    public JPVehiculo() {
        initComponents();
        vehiculoControlador = new VehiculoControlador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFModelo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFLinea = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFMarca = new javax.swing.JTextField();
        jTFNoChasis = new javax.swing.JTextField();
        jTFColor = new javax.swing.JTextField();
        jTFCojineria = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCBDisponible = new javax.swing.JComboBox();
        jBLimpiar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Crear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jBConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTResultados = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTFLinea1 = new javax.swing.JTextField();
        jTFMarca1 = new javax.swing.JTextField();
        jTFNoChasis1 = new javax.swing.JTextField();
        jTFModelo1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTFColor1 = new javax.swing.JTextField();
        jBLimpiarConsultar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jBModificar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTFModelo2 = new javax.swing.JTextField();
        jTFLinea2 = new javax.swing.JTextField();
        jTFMarca2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jCBDisponible1 = new javax.swing.JComboBox();
        jTFCojineria1 = new javax.swing.JTextField();
        jTFColor2 = new javax.swing.JTextField();
        jTFNoChasis2 = new javax.swing.JTextField();

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));
        jPanel5.setLayout(null);
        jPanel5.add(jLabel13);
        jLabel13.setBounds(18, 182, 0, 0);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Vehiculo"));
        jPanel4.setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText("Modelo");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 20, 160, 14);

        jTFModelo.setColumns(20);
        jPanel1.add(jTFModelo);
        jTFModelo.setBounds(170, 10, 166, 20);

        jLabel2.setText("Linea");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 50, 150, 14);

        jTFLinea.setColumns(20);
        jPanel1.add(jTFLinea);
        jTFLinea.setBounds(170, 40, 166, 20);

        jLabel3.setText("Marca");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 80, 150, 14);

        jTFMarca.setColumns(20);
        jPanel1.add(jTFMarca);
        jTFMarca.setBounds(170, 70, 166, 20);

        jTFNoChasis.setColumns(20);
        jPanel1.add(jTFNoChasis);
        jTFNoChasis.setBounds(170, 100, 166, 20);

        jTFColor.setColumns(20);
        jPanel1.add(jTFColor);
        jTFColor.setBounds(170, 130, 166, 20);

        jTFCojineria.setColumns(20);
        jPanel1.add(jTFCojineria);
        jTFCojineria.setBounds(170, 160, 166, 26);

        jLabel4.setText("No. Chasis");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 110, 150, 14);

        jLabel5.setText("Color");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 140, 150, 14);

        jLabel7.setText("Cojineria");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 170, 150, 14);

        jCBDisponible.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "True", "False" }));
        jCBDisponible.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCBDisponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBDisponibleActionPerformed(evt);
            }
        });
        jPanel1.add(jCBDisponible);
        jCBDisponible.setBounds(170, 200, 120, 20);

        jBLimpiar.setText("Limpiar");
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(jBLimpiar);
        jBLimpiar.setBounds(250, 250, 90, 23);

        jLabel6.setText("Disponible");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 210, 150, 14);

        Crear.setText("Crear");
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });
        jPanel1.add(Crear);
        Crear.setBounds(160, 250, 90, 23);

        jTabbedPane1.addTab("Crear", jPanel1);

        jPanel2.setLayout(null);

        jBConsultar.setText("Consultar");
        jBConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarActionPerformed(evt);
            }
        });
        jPanel2.add(jBConsultar);
        jBConsultar.setBounds(380, 10, 90, 23);

        jTResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Chasis", "Linea", "Marca", "Color", "Modelo", "Cojineria", "Disponible"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTResultadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTResultados);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 170, 550, 125);

        jLabel20.setText("No. Chasis");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(10, 110, 130, 14);

        jLabel21.setText("Marca");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(10, 80, 130, 14);

        jLabel22.setText("Linea");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(10, 50, 130, 14);

        jTFLinea1.setColumns(20);
        jPanel2.add(jTFLinea1);
        jTFLinea1.setBounds(160, 40, 166, 20);

        jTFMarca1.setColumns(20);
        jPanel2.add(jTFMarca1);
        jTFMarca1.setBounds(160, 70, 166, 20);

        jTFNoChasis1.setColumns(20);
        jPanel2.add(jTFNoChasis1);
        jTFNoChasis1.setBounds(160, 100, 166, 20);

        jTFModelo1.setColumns(20);
        jPanel2.add(jTFModelo1);
        jTFModelo1.setBounds(160, 10, 166, 20);

        jLabel23.setText("Modelo");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(10, 20, 130, 14);

        jLabel24.setText("Color");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(10, 140, 130, 14);

        jTFColor1.setColumns(20);
        jPanel2.add(jTFColor1);
        jTFColor1.setBounds(160, 130, 166, 20);

        jBLimpiarConsultar.setText("Limpiar");
        jBLimpiarConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarConsultarActionPerformed(evt);
            }
        });
        jPanel2.add(jBLimpiarConsultar);
        jBLimpiarConsultar.setBounds(380, 40, 90, 23);

        jTabbedPane1.addTab("Consultar", jPanel2);

        jPanel3.setLayout(null);

        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });
        jPanel3.add(jBModificar);
        jBModificar.setBounds(220, 250, 90, 23);

        jLabel8.setText("Modelo");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(10, 20, 130, 14);

        jTFModelo2.setColumns(20);
        jPanel3.add(jTFModelo2);
        jTFModelo2.setBounds(150, 20, 166, 20);

        jTFLinea2.setColumns(20);
        jPanel3.add(jTFLinea2);
        jTFLinea2.setBounds(150, 50, 166, 20);

        jTFMarca2.setColumns(20);
        jPanel3.add(jTFMarca2);
        jTFMarca2.setBounds(150, 80, 166, 20);

        jLabel9.setText("Linea");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(10, 50, 130, 14);

        jLabel16.setText("Marca");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(10, 80, 120, 14);

        jLabel25.setText("No. Chasis");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(10, 110, 130, 14);

        jLabel26.setText("Color");
        jPanel3.add(jLabel26);
        jLabel26.setBounds(10, 140, 130, 14);

        jLabel27.setText("Cojineria");
        jPanel3.add(jLabel27);
        jLabel27.setBounds(10, 170, 120, 14);

        jLabel29.setText("Disponible");
        jPanel3.add(jLabel29);
        jLabel29.setBounds(10, 200, 120, 14);

        jCBDisponible1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "True", "False" }));
        jPanel3.add(jCBDisponible1);
        jCBDisponible1.setBounds(150, 210, 120, 20);

        jTFCojineria1.setColumns(20);
        jPanel3.add(jTFCojineria1);
        jTFCojineria1.setBounds(150, 170, 166, 26);

        jTFColor2.setColumns(20);
        jPanel3.add(jTFColor2);
        jTFColor2.setBounds(150, 140, 166, 20);

        jTFNoChasis2.setColumns(20);
        jTFNoChasis2.setEditable(false);
        jPanel3.add(jTFNoChasis2);
        jTFNoChasis2.setBounds(150, 110, 166, 20);

        jTabbedPane1.addTab("Modificar", jPanel3);

        jPanel4.add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 20, 608, 340);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        jCBDisponible.setSelectedIndex(0);
        jTFCojineria.setText("");
        jTFColor.setText("");
        jTFLinea.setText("");
        jTFMarca.setText("");
        jTFModelo.setText("");
        jTFNoChasis.setText("");
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        // TODO add your handling code here:
        int editar = -1;
        Boolean disponible=null;
        try {
            if (jCBDisponible1.getSelectedIndex() == 0) {
                disponible=null;
            }
            if (jCBDisponible1.getSelectedIndex() == 1) {
                disponible=true;
            }
            if (jCBDisponible1.getSelectedIndex() == 2) {
                disponible=false;
            }
            
            editar = vehiculoControlador.editar(Integer.parseInt(jTFNoChasis2.getText()),
                    jTFLinea2.getText(),
                    jTFMarca2.getText(),
                    jTFColor2.getText(),
                    jTFModelo2.getText(),
                    jTFCojineria1.getText(),
                    disponible);

        } catch (Exception e) {
            System.out.print(e);
        }
        if (editar == -1) {
            JOptionPane.showMessageDialog(this, "No su pudo modificar el vehiculo", "Error Base Datos", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Vehiculo modificado correctamente", "Base Datos", JOptionPane.INFORMATION_MESSAGE);
            limpiarCamposConsultar();
            jTFNoChasis1.setText(jTFNoChasis2.getText());
            jBConsultar.doClick();
            jTabbedPane1.setSelectedIndex(1);
            limpiarCamposModificar();
        }
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBLimpiarConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarConsultarActionPerformed
        limpiarCamposConsultar();
        jBConsultar.doClick();
    }//GEN-LAST:event_jBLimpiarConsultarActionPerformed

    private void jBConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarActionPerformed
        // TODO add your handling code here:
        LinkedList consulta = new LinkedList();
        try {
            consulta = vehiculoControlador.consultar(jTFNoChasis1.getText(), jTFMarca1.getText(), jTFModelo1.getText(), jTFLinea1.getText(),
                    jTFColor1.getText());
            Object[][] s = new Object[consulta.size()][7];
            for (int i = 0; i < consulta.size(); i++) {
                Vehiculo v = (Vehiculo) consulta.get(i);

                if (!v.getModelo_v().isEmpty()) {
                    s[i][0] = v.getNumerochasis_v();
                    s[i][1] = v.getLinea_v();
                    s[i][2] = v.getMarca_v();
                    s[i][3] = v.getColor_v();
                    s[i][4] = v.getModelo_v();
                    s[i][5] = v.getCojineria_v();
                    s[i][6] = v.getDisponible_v();
                } else {
                    s = null;
                }
            }
            TableModel myModel = new DefaultTableModel(s, new String[]{"No Chasis", "Linea", "Marca", "Color", "Modelo", "Cojineria", "Disponible"}) {

                boolean[] canEdit = new boolean[]{false, false, false, false, false, false, false
                };

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            };
            ///remover filas
            jTResultados.setModel(myModel);
            jTResultados.setRowSorter(new TableRowSorter(myModel));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBConsultarActionPerformed

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
        // TODO add your handling code here:
        int guardar = -1;
        Boolean disponible = null;
        System.out.println(guardar);
        try {
            if (jCBDisponible.getSelectedIndex() == 0) {
                disponible=null;
            }
            if (jCBDisponible.getSelectedIndex() == 1) {
                disponible=true;
            }
            if (jCBDisponible.getSelectedIndex() == 2) {
                disponible=false;
            }
           
            
            
            guardar = vehiculoControlador.guardar(
                    Integer.parseInt(jTFNoChasis.getText()),
                    jTFLinea.getText(),
                    jTFMarca.getText(),
                    jTFColor.getText(),
                    jTFModelo.getText(),
                    jTFCojineria.getText(),
                    disponible);
            

        } catch (Exception e) {
            System.err.println(guardar);
        }

        if (guardar == -1) {
            System.out.println(guardar);
            JOptionPane.showMessageDialog(this, "No su pudo crear el Vehiculo", "Error Base Datos", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Vehiculo creado correctamente", "Base Datos", JOptionPane.INFORMATION_MESSAGE);
            jTFNoChasis1.setText(jTFNoChasis.getText());
            jBConsultar.doClick();
            jBLimpiar.doClick();
            jTabbedPane1.setSelectedIndex(1);

        }


    }//GEN-LAST:event_CrearActionPerformed

    private void jCBDisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBDisponibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBDisponibleActionPerformed

    private void jTResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTResultadosMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTResultados.getSelectedRow();
        jTFNoChasis2.setText("" + jTResultados.getModel().getValueAt(selectedRow, 0));
        jTFLinea2.setText("" + jTResultados.getModel().getValueAt(selectedRow, 1));
        jTFMarca2.setText("" + jTResultados.getModel().getValueAt(selectedRow, 2));
        jTFColor2.setText("" + jTResultados.getModel().getValueAt(selectedRow, 3));
        jTFModelo2.setText("" + jTResultados.getModel().getValueAt(selectedRow, 4));
        jTFCojineria1.setText("" + jTResultados.getModel().getValueAt(selectedRow, 5));
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jTResultadosMouseClicked
    private void limpiarCamposModificar() {
        jTFMarca2.setText("");
        jTFLinea2.setText("");
        jTFModelo2.setText("");
        jTFNoChasis2.setText("");
        jTFColor2.setText("");
        jTFCojineria1.setText("");
        jCBDisponible1.setSelectedIndex(0);

    }

    private void limpiarCamposCrear() {
        jTFMarca.setText("");
        jTFLinea.setText("");
        jTFModelo.setText("");
        jTFNoChasis.setText("");
        jTFColor.setText("");
        jTFCojineria.setText("");
        jCBDisponible.setSelectedIndex(0);
    }

    private void limpiarCamposConsultar() {
        jTFMarca1.setText("");
        jTFLinea1.setText("");
        jTFModelo1.setText("");
        jTFNoChasis1.setText("");
        jTFColor1.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Crear;
    private javax.swing.JButton jBConsultar;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JButton jBLimpiarConsultar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JComboBox jCBDisponible;
    private javax.swing.JComboBox jCBDisponible1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCojineria;
    private javax.swing.JTextField jTFCojineria1;
    private javax.swing.JTextField jTFColor;
    private javax.swing.JTextField jTFColor1;
    private javax.swing.JTextField jTFColor2;
    private javax.swing.JTextField jTFLinea;
    private javax.swing.JTextField jTFLinea1;
    private javax.swing.JTextField jTFLinea2;
    private javax.swing.JTextField jTFMarca;
    private javax.swing.JTextField jTFMarca1;
    private javax.swing.JTextField jTFMarca2;
    private javax.swing.JTextField jTFModelo;
    private javax.swing.JTextField jTFModelo1;
    private javax.swing.JTextField jTFModelo2;
    private javax.swing.JTextField jTFNoChasis;
    private javax.swing.JTextField jTFNoChasis1;
    private javax.swing.JTextField jTFNoChasis2;
    private javax.swing.JTable jTResultados;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
