/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package desarrollogui;

import desarrollogui.Cliente.JPBuscarCliente;
import desarrollogui.Cliente.JPCrearCliente;
import desarrollogui.Cliente.JPModificarCliente;
import desarrollogui.Item.JPCrearItem;
import desarrollogui.Item.JPEliminarItem;
import desarrollogui.Item.JPModificarItem;
import desarrollogui.Ordenes.JPOrdenAlistamiento;
import desarrollogui.Ordenes.JPOrdenReparacion;
import java.awt.BorderLayout;
import java.awt.FlowLayout;

/**
 *
 * @author juandapp
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        jPPrincipal.setLayout(new FlowLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMCrearCliente = new javax.swing.JMenu();
        jMICrearCliente = new javax.swing.JMenuItem();
        jMIModificarCliente = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMIBuscarCliente = new javax.swing.JMenuItem();
        jMInventario = new javax.swing.JMenu();
        jMICrearItem = new javax.swing.JMenuItem();
        jMIModificarItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMIEliminarItem = new javax.swing.JMenuItem();
        jMOrdenesTrabajo = new javax.swing.JMenu();
        jMIOrdenAlistamiento = new javax.swing.JMenuItem();
        jMIOrdenReparacion = new javax.swing.JMenuItem();
        jMIOrdenMantenimiento = new javax.swing.JMenuItem();
        jMOpciones = new javax.swing.JMenu();
        jMIModificarOpcionesPersonales = new javax.swing.JMenuItem();
        jMVentas = new javax.swing.JMenu();
        jMICrearCotizacion = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMIRegistrarVenta = new javax.swing.JMenuItem();
        jMUsuarios = new javax.swing.JMenu();
        jMICrearUsuario = new javax.swing.JMenuItem();
        jMIModificarUsuario = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMIEliminarUsuario = new javax.swing.JMenuItem();
        jMReportes = new javax.swing.JMenu();
        jMIGenerarReporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPPrincipal.setLayout(null);

        jLabel1.setText("Principal");
        jPPrincipal.add(jLabel1);
        jLabel1.setBounds(280, 180, 59, 30);

        jMCrearCliente.setText(" Cliente ");

        jMICrearCliente.setText("Crear Cliente");
        jMICrearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICrearClienteActionPerformed(evt);
            }
        });
        jMCrearCliente.add(jMICrearCliente);

        jMIModificarCliente.setText("Modificar Cliente");
        jMIModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIModificarClienteActionPerformed(evt);
            }
        });
        jMCrearCliente.add(jMIModificarCliente);
        jMCrearCliente.add(jSeparator5);

        jMIBuscarCliente.setText("Buscar Cliente");
        jMIBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIBuscarClienteActionPerformed(evt);
            }
        });
        jMCrearCliente.add(jMIBuscarCliente);

        jMenuBar1.add(jMCrearCliente);

        jMInventario.setText(" Inventario ");

        jMICrearItem.setText("Crear Item");
        jMICrearItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICrearItemActionPerformed(evt);
            }
        });
        jMInventario.add(jMICrearItem);

        jMIModificarItem.setText("Modificar Item");
        jMIModificarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIModificarItemActionPerformed(evt);
            }
        });
        jMInventario.add(jMIModificarItem);
        jMInventario.add(jSeparator2);

        jMIEliminarItem.setText("Eliminar Item");
        jMIEliminarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIEliminarItemActionPerformed(evt);
            }
        });
        jMInventario.add(jMIEliminarItem);

        jMenuBar1.add(jMInventario);

        jMOrdenesTrabajo.setText(" Ordenes Trabajo  ");

        jMIOrdenAlistamiento.setText("Orden Alistamiento");
        jMIOrdenAlistamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIOrdenAlistamientoActionPerformed(evt);
            }
        });
        jMOrdenesTrabajo.add(jMIOrdenAlistamiento);

        jMIOrdenReparacion.setText("Orden Reparacion");
        jMIOrdenReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIOrdenReparacionActionPerformed(evt);
            }
        });
        jMOrdenesTrabajo.add(jMIOrdenReparacion);

        jMIOrdenMantenimiento.setText("Orden Mantenimiento");
        jMIOrdenMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIOrdenMantenimientoActionPerformed(evt);
            }
        });
        jMOrdenesTrabajo.add(jMIOrdenMantenimiento);

        jMenuBar1.add(jMOrdenesTrabajo);

        jMOpciones.setText("Opciones  ");

        jMIModificarOpcionesPersonales.setText("Modificar Opciones Personales");
        jMIModificarOpcionesPersonales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIModificarOpcionesPersonalesActionPerformed(evt);
            }
        });
        jMOpciones.add(jMIModificarOpcionesPersonales);

        jMenuBar1.add(jMOpciones);

        jMVentas.setText(" Ventas  ");

        jMICrearCotizacion.setText("Crear Cotizacion");
        jMICrearCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICrearCotizacionActionPerformed(evt);
            }
        });
        jMVentas.add(jMICrearCotizacion);
        jMVentas.add(jSeparator3);

        jMIRegistrarVenta.setText("Registrar Venta");
        jMIRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRegistrarVentaActionPerformed(evt);
            }
        });
        jMVentas.add(jMIRegistrarVenta);

        jMenuBar1.add(jMVentas);

        jMUsuarios.setText(" Usuarios  ");

        jMICrearUsuario.setText("Crear Usuario");
        jMICrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICrearUsuarioActionPerformed(evt);
            }
        });
        jMUsuarios.add(jMICrearUsuario);

        jMIModificarUsuario.setText("Modificar Usuario");
        jMIModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIModificarUsuarioActionPerformed(evt);
            }
        });
        jMUsuarios.add(jMIModificarUsuario);
        jMUsuarios.add(jSeparator4);

        jMIEliminarUsuario.setText("Eliminar Usuario");
        jMIEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIEliminarUsuarioActionPerformed(evt);
            }
        });
        jMUsuarios.add(jMIEliminarUsuario);

        jMenuBar1.add(jMUsuarios);

        jMReportes.setText(" Reportes  ");

        jMIGenerarReporte.setText("Generar Reporte");
        jMIGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIGenerarReporteActionPerformed(evt);
            }
        });
        jMReportes.add(jMIGenerarReporte);

        jMenuBar1.add(jMReportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMICrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICrearClienteActionPerformed
        try {
            jPPrincipal.removeAll();
        } catch (Exception e) {
        }
        JPCrearCliente jPCC = new JPCrearCliente();
        jPPrincipal.add(jPCC, BorderLayout.CENTER);
        jPPrincipal.updateUI();
        this.pack();
    }//GEN-LAST:event_jMICrearClienteActionPerformed

    private void jMIModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIModificarClienteActionPerformed
        try {
            jPPrincipal.removeAll();
        } catch (Exception e) {
        }
        JPModificarCliente jPMC = new JPModificarCliente();
        jPPrincipal.add(jPMC, BorderLayout.CENTER);
        jPPrincipal.updateUI();
        this.pack();
    }//GEN-LAST:event_jMIModificarClienteActionPerformed

    private void jMIBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIBuscarClienteActionPerformed
        try {
            jPPrincipal.removeAll();
        } catch (Exception e) {
        }
        JPBuscarCliente jPBC = new JPBuscarCliente();
        jPPrincipal.add(jPBC, BorderLayout.CENTER);
        jPPrincipal.updateUI();
        this.pack();
    }//GEN-LAST:event_jMIBuscarClienteActionPerformed

    private void jMICrearItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICrearItemActionPerformed
        try {
            jPPrincipal.removeAll();
        } catch (Exception e) {
        }
        JPCrearItem jPCI = new JPCrearItem();
        jPPrincipal.add(jPCI, BorderLayout.CENTER);
        jPPrincipal.updateUI();
        this.pack();
    }//GEN-LAST:event_jMICrearItemActionPerformed

    private void jMIModificarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIModificarItemActionPerformed
        try {
            jPPrincipal.removeAll();
        } catch (Exception e) {
        }
        JPModificarItem jPMI = new JPModificarItem();
        jPPrincipal.add(jPMI, BorderLayout.CENTER);
        jPPrincipal.updateUI();
        this.pack();
    }//GEN-LAST:event_jMIModificarItemActionPerformed

    private void jMIEliminarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIEliminarItemActionPerformed
        try {
            jPPrincipal.removeAll();
        } catch (Exception e) {
        }
        JPEliminarItem jPEI = new JPEliminarItem();
        jPPrincipal.add(jPEI, BorderLayout.CENTER);
        jPPrincipal.updateUI();
        this.pack();
    }//GEN-LAST:event_jMIEliminarItemActionPerformed

    private void jMIOrdenAlistamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIOrdenAlistamientoActionPerformed
        try {
            jPPrincipal.removeAll();
        } catch (Exception e) {
        }
        JPOrdenAlistamiento jPOA = new JPOrdenAlistamiento();
        jPPrincipal.add(jPOA, BorderLayout.CENTER);
        jPPrincipal.updateUI();
        this.pack();
    }//GEN-LAST:event_jMIOrdenAlistamientoActionPerformed

    private void jMIOrdenReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIOrdenReparacionActionPerformed
        try {
            jPPrincipal.removeAll();
        } catch (Exception e) {
        }
        JPOrdenReparacion jPOR = new JPOrdenReparacion();
        jPPrincipal.add(jPOR, BorderLayout.CENTER);
        jPPrincipal.updateUI();
        this.pack();
    }//GEN-LAST:event_jMIOrdenReparacionActionPerformed

    private void jMIOrdenMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIOrdenMantenimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIOrdenMantenimientoActionPerformed

    private void jMICrearCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICrearCotizacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMICrearCotizacionActionPerformed

    private void jMIRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRegistrarVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIRegistrarVentaActionPerformed

    private void jMICrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICrearUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMICrearUsuarioActionPerformed

    private void jMIModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIModificarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIModificarUsuarioActionPerformed

    private void jMIEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIEliminarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIEliminarUsuarioActionPerformed

    private void jMIGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIGenerarReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIGenerarReporteActionPerformed

    private void jMIModificarOpcionesPersonalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIModificarOpcionesPersonalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIModificarOpcionesPersonalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GUI().setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMCrearCliente;
    private javax.swing.JMenuItem jMIBuscarCliente;
    private javax.swing.JMenuItem jMICrearCliente;
    private javax.swing.JMenuItem jMICrearCotizacion;
    private javax.swing.JMenuItem jMICrearItem;
    private javax.swing.JMenuItem jMICrearUsuario;
    private javax.swing.JMenuItem jMIEliminarItem;
    private javax.swing.JMenuItem jMIEliminarUsuario;
    private javax.swing.JMenuItem jMIGenerarReporte;
    private javax.swing.JMenuItem jMIModificarCliente;
    private javax.swing.JMenuItem jMIModificarItem;
    private javax.swing.JMenuItem jMIModificarOpcionesPersonales;
    private javax.swing.JMenuItem jMIModificarUsuario;
    private javax.swing.JMenuItem jMIOrdenAlistamiento;
    private javax.swing.JMenuItem jMIOrdenMantenimiento;
    private javax.swing.JMenuItem jMIOrdenReparacion;
    private javax.swing.JMenuItem jMIRegistrarVenta;
    private javax.swing.JMenu jMInventario;
    private javax.swing.JMenu jMOpciones;
    private javax.swing.JMenu jMOrdenesTrabajo;
    private javax.swing.JMenu jMReportes;
    private javax.swing.JMenu jMUsuarios;
    private javax.swing.JMenu jMVentas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPPrincipal;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
