/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package desarrollogui;

/**
 *
 * @author juandapp
 */
public class JPAccesorio extends javax.swing.JPanel {

    /**
     * Creates new form JPCliente
     */
    public JPAccesorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFCodigo = new javax.swing.JTextField();
        jTFNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFCantidad = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTPDescripcion = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jBLimpiar = new javax.swing.JButton();
        jBCrear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jBConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTResultados = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTFCodigo1 = new javax.swing.JTextField();
        jTFNombre1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jBModificar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTFCodigo2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFNombre3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTFCantidad1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTPDescripcion1 = new javax.swing.JTextPane();

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));
        jPanel5.setLayout(null);
        jPanel5.add(jLabel13);
        jLabel13.setBounds(18, 182, 0, 0);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Accesorio"));
        jPanel4.setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText("Codigo");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 20, 49, 18);

        jTFCodigo.setColumns(20);
        jPanel1.add(jTFCodigo);
        jTFCodigo.setBounds(100, 10, 270, 28);

        jTFNombre.setColumns(20);
        jPanel1.add(jTFNombre);
        jTFNombre.setBounds(100, 40, 270, 28);

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 50, 57, 18);

        jLabel3.setText("Cantidad");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 80, 62, 18);

        jTFCantidad.setColumns(20);
        jPanel1.add(jTFCantidad);
        jTFCantidad.setBounds(100, 70, 100, 28);

        jScrollPane2.setViewportView(jTPDescripcion);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(100, 100, 270, 72);

        jLabel4.setText("Descripcion");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 110, 82, 18);

        jBLimpiar.setText("Limpiar");
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(jBLimpiar);
        jBLimpiar.setBounds(290, 180, 80, 30);

        jBCrear.setText("Crear");
        jPanel1.add(jBCrear);
        jBCrear.setBounds(200, 180, 70, 30);

        jTabbedPane1.addTab("Crear", jPanel1);

        jPanel2.setLayout(null);

        jBConsultar.setText("Consultar");
        jPanel2.add(jBConsultar);
        jBConsultar.setBounds(380, 10, 90, 30);

        jTResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Cantidad", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTResultados);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 80, 470, 125);

        jLabel5.setText("Codigo");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 20, 49, 18);

        jTFCodigo1.setColumns(20);
        jPanel2.add(jTFCodigo1);
        jTFCodigo1.setBounds(80, 10, 270, 28);

        jTFNombre1.setColumns(20);
        jPanel2.add(jTFNombre1);
        jTFNombre1.setBounds(80, 40, 270, 28);

        jLabel6.setText("Nombre");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 50, 57, 18);

        jTabbedPane1.addTab("Consultar", jPanel2);

        jPanel3.setLayout(null);

        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });
        jPanel3.add(jBModificar);
        jBModificar.setBounds(290, 180, 90, 30);

        jLabel7.setText("Codigo");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 20, 49, 18);

        jTFCodigo2.setColumns(20);
        jPanel3.add(jTFCodigo2);
        jTFCodigo2.setBounds(110, 10, 270, 28);

        jLabel8.setText("Nombre");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(20, 50, 57, 18);

        jTFNombre3.setColumns(20);
        jPanel3.add(jTFNombre3);
        jTFNombre3.setBounds(110, 40, 270, 28);

        jLabel9.setText("Cantidad");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 80, 62, 18);

        jTFCantidad1.setColumns(20);
        jPanel3.add(jTFCantidad1);
        jTFCantidad1.setBounds(110, 70, 100, 28);

        jLabel15.setText("Descripcion");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(20, 110, 82, 18);

        jScrollPane3.setViewportView(jTPDescripcion1);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(110, 100, 270, 72);

        jTabbedPane1.addTab("Modificar", jPanel3);

        jPanel4.add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 20, 524, 267);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        jTPDescripcion.setText("");
        jTFNombre.setText("");
        jTFCantidad.setText("");
        jTFCodigo.setText("");

    }//GEN-LAST:event_jBLimpiarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConsultar;
    private javax.swing.JButton jBCrear;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTFCantidad;
    private javax.swing.JTextField jTFCantidad1;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JTextField jTFCodigo1;
    private javax.swing.JTextField jTFCodigo2;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFNombre1;
    private javax.swing.JTextField jTFNombre3;
    private javax.swing.JTextPane jTPDescripcion;
    private javax.swing.JTextPane jTPDescripcion1;
    private javax.swing.JTable jTResultados;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
