/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package desarrollogui;

/**
 *
 * @author juandapp
 */
public class JPVehiculo extends javax.swing.JPanel {

    /**
     * Creates new form JPCliente
     */
    public JPVehiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFModelo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFLinea = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFMarca = new javax.swing.JTextField();
        jTFNoChasis = new javax.swing.JTextField();
        jTFColor = new javax.swing.JTextField();
        jTFCojineria = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCBDisponible = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jBLimpiar = new javax.swing.JButton();
        jBCrear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jCBTipoCaja1 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jBConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTResultados = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTFLinea1 = new javax.swing.JTextField();
        jTFMarca1 = new javax.swing.JTextField();
        jTFNoChasis1 = new javax.swing.JTextField();
        jTFModelo1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTFColor1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jTFIdentificacion2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTFNombre2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jCBGenero1 = new javax.swing.JComboBox();
        jTFFechaNacimiento1 = new javax.swing.JTextField();
        jTFTelefono1 = new javax.swing.JTextField();
        jTFDireccion1 = new javax.swing.JTextField();
        jTFEmail1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jBModificar = new javax.swing.JButton();

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));
        jPanel5.setLayout(null);
        jPanel5.add(jLabel13);
        jLabel13.setBounds(18, 182, 0, 0);

        jPanel1.setLayout(null);

        jLabel1.setText("Modelo");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 20, 53, 18);

        jTFModelo.setColumns(20);
        jPanel1.add(jTFModelo);
        jTFModelo.setBounds(90, 10, 270, 28);

        jLabel2.setText("Linea");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 50, 37, 18);

        jTFLinea.setColumns(20);
        jPanel1.add(jTFLinea);
        jTFLinea.setBounds(90, 40, 270, 28);

        jLabel3.setText("Marca");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 80, 43, 18);

        jTFMarca.setColumns(20);
        jPanel1.add(jTFMarca);
        jTFMarca.setBounds(90, 70, 270, 28);

        jTFNoChasis.setColumns(20);
        jPanel1.add(jTFNoChasis);
        jTFNoChasis.setBounds(90, 100, 270, 28);

        jTFColor.setColumns(20);
        jPanel1.add(jTFColor);
        jTFColor.setBounds(90, 130, 270, 28);

        jTFCojineria.setColumns(20);
        jPanel1.add(jTFCojineria);
        jTFCojineria.setBounds(90, 160, 270, 26);

        jLabel4.setText("No. Chasis");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 110, 71, 18);

        jLabel5.setText("Color");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 140, 38, 18);

        jLabel7.setText("Cojineria");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 170, 60, 18);

        jCBDisponible.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "True", "False" }));
        jPanel1.add(jCBDisponible);
        jCBDisponible.setBounds(90, 220, 120, 28);

        jLabel15.setText("Tipo Caja");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(10, 200, 62, 18);

        jBLimpiar.setText("Limpiar");
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(jBLimpiar);
        jBLimpiar.setBounds(142, 260, 90, 30);

        jBCrear.setText("Crear");
        jPanel1.add(jBCrear);
        jBCrear.setBounds(240, 260, 70, 30);

        jLabel6.setText("Disponible");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 230, 73, 18);

        jCBTipoCaja1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Automatico", "Mecanico" }));
        jPanel1.add(jCBTipoCaja1);
        jCBTipoCaja1.setBounds(90, 190, 118, 28);

        jTabbedPane1.addTab("Crear", jPanel1);

        jPanel2.setLayout(null);

        jBConsultar.setText("Consultar");
        jPanel2.add(jBConsultar);
        jBConsultar.setBounds(380, 10, 90, 30);

        jTResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Chasis", "Linea", "Marca", "Color", "Modelo", "Cojineria", "Disponible"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTResultados);
        jTResultados.getColumnModel().getColumn(4).setResizable(false);
        jTResultados.getColumnModel().getColumn(5).setResizable(false);
        jTResultados.getColumnModel().getColumn(6).setResizable(false);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 170, 550, 125);

        jLabel20.setText("No. Chasis");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(10, 110, 71, 18);

        jLabel21.setText("Marca");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(10, 80, 43, 18);

        jLabel22.setText("Linea");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(10, 50, 37, 18);

        jTFLinea1.setColumns(20);
        jPanel2.add(jTFLinea1);
        jTFLinea1.setBounds(90, 40, 270, 28);

        jTFMarca1.setColumns(20);
        jPanel2.add(jTFMarca1);
        jTFMarca1.setBounds(90, 70, 270, 28);

        jTFNoChasis1.setColumns(20);
        jPanel2.add(jTFNoChasis1);
        jTFNoChasis1.setBounds(90, 100, 270, 28);

        jTFModelo1.setColumns(20);
        jPanel2.add(jTFModelo1);
        jTFModelo1.setBounds(90, 10, 270, 28);

        jLabel23.setText("Modelo");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(10, 20, 53, 18);

        jLabel24.setText("Color");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(10, 140, 38, 18);

        jTFColor1.setColumns(20);
        jPanel2.add(jTFColor1);
        jTFColor1.setBounds(90, 130, 270, 28);

        jTabbedPane1.addTab("Consultar", jPanel2);

        jPanel3.setLayout(null);

        jLabel19.setText("Identificacion");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(10, 20, 93, 18);

        jTFIdentificacion2.setColumns(20);
        jPanel3.add(jTFIdentificacion2);
        jTFIdentificacion2.setBounds(160, 10, 270, 28);

        jLabel10.setText("Nombre");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 50, 57, 18);

        jTFNombre2.setColumns(20);
        jPanel3.add(jTFNombre2);
        jTFNombre2.setBounds(160, 40, 270, 28);

        jLabel12.setText("Genero");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(10, 80, 52, 18);

        jCBGenero1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Femenino", "Masculino" }));
        jCBGenero1.setName(""); // NOI18N
        jPanel3.add(jCBGenero1);
        jCBGenero1.setBounds(160, 70, 119, 28);

        jTFFechaNacimiento1.setColumns(20);
        jPanel3.add(jTFFechaNacimiento1);
        jTFFechaNacimiento1.setBounds(160, 100, 270, 28);

        jTFTelefono1.setColumns(20);
        jPanel3.add(jTFTelefono1);
        jTFTelefono1.setBounds(160, 130, 270, 28);

        jTFDireccion1.setColumns(20);
        jPanel3.add(jTFDireccion1);
        jTFDireccion1.setBounds(160, 160, 270, 28);

        jTFEmail1.setColumns(20);
        jPanel3.add(jTFEmail1);
        jTFEmail1.setBounds(160, 190, 270, 28);

        jLabel18.setText("Email");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(10, 200, 37, 18);

        jLabel17.setText("Direccion");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(10, 170, 66, 18);

        jLabel11.setText("Telefono");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 140, 64, 18);

        jLabel14.setText("Fecha de nacimiento");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(10, 110, 143, 18);

        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });
        jPanel3.add(jBModificar);
        jBModificar.setBounds(331, 230, 90, 30);

        jTabbedPane1.addTab("Modificar", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        jCBDisponible.setSelectedIndex(0);
        jTFCojineria.setText("");
        jTFColor.setText("");
        jTFLinea.setText("");
        jTFMarca.setText("");
        jTFModelo.setText("");
        jTFNoChasis.setText("");
    }//GEN-LAST:event_jBLimpiarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConsultar;
    private javax.swing.JButton jBCrear;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JComboBox jCBDisponible;
    private javax.swing.JComboBox jCBGenero1;
    private javax.swing.JComboBox jCBTipoCaja1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCojineria;
    private javax.swing.JTextField jTFColor;
    private javax.swing.JTextField jTFColor1;
    private javax.swing.JTextField jTFDireccion1;
    private javax.swing.JTextField jTFEmail1;
    private javax.swing.JTextField jTFFechaNacimiento1;
    private javax.swing.JTextField jTFIdentificacion2;
    private javax.swing.JTextField jTFLinea;
    private javax.swing.JTextField jTFLinea1;
    private javax.swing.JTextField jTFMarca;
    private javax.swing.JTextField jTFMarca1;
    private javax.swing.JTextField jTFModelo;
    private javax.swing.JTextField jTFModelo1;
    private javax.swing.JTextField jTFNoChasis;
    private javax.swing.JTextField jTFNoChasis1;
    private javax.swing.JTextField jTFNombre2;
    private javax.swing.JTextField jTFTelefono1;
    private javax.swing.JTable jTResultados;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
